-- Birding Log Data
-- coding: utf-8 'ä

BL_BirdingKit = 104 -- item category
BL_Found = "You have acquired: "
BL_Loc = ";loc"
BL_Region = { Eriador=1, Rhovanion=2, Gondor=3, Mordor=4, Haradwaith=5 }
BL_RegN = {}
for name,ix in pairs(BL_Region) do BL_RegN[ix] = name end

BL_Zone = {
		['Ag']={z="Agarnaith", r=4, n=-46, s=-57, e=37, w=25 },
		['An']={z="Angmar", r=1, n=13, s=-4, e=-15, w=-41 },
		['Ar']={z="Anorien", r=3, n=-40, s=-72, e=-13, w=-47 },
		['Bf']={z="Belfalas", r=3, n=-72, s=-93.4, e=-60, w=-74 },
		['Br']={z="Bree-land", r=1, n=-18.5, s=-37, e=-42, w=-63 },
		['Ca']={z="Cardolan", r=1, n=-37, s=-55, e=-28, w=-56 },
		['Cl']={z="Croftlands", r=2, n=-43, s=-65, e=-52, w=-65 },
		['Du']={z="Dunland", r=1, n=-75, s=-90, e=1, w=-26 },
		['Ef']={z="Eastfold", r=2, n=-53, s=-74, e=-53, w=-76.4 },
		['En']={z="Enedwaith", r=1, n=-57, s=-75, e=-9, w=-24 },
		['EL']={z="Ered Luin", r=1, n=-13, s=-29, e=-89, w=-108 },
		['Er']={z="Eregion", r=1, n=-40, s=-57, e=-6, w=-19 },
		['Ev']={z="Evendim", r=1, n=-3, s=-20, e=-60, w=-76 },
		['Ew']={z="Entwash", r=2, n=-40, s=-53, e=-59, w=-76 },
		['Fg']={z="Fangorn", r=2, n=-37.5, s=-44, e=-78, w=-85 },
		['Fo']={z="Forochel", r=1, n=21, s=-3, e=-57, w=-89 },
		['GR']={z="Great River", r=2, n=-19.5, s=-33, e=-48, w=-72 },
		['It']={z="Ithilien", r=3, n=-41, s=-77, e=-3, w=-19 },
		['Ld']={z="Lamedon", r=3, n=-60, s=-72, e=-54, w=-62 },
		['Le']={z="Lebennin", r=3, n=-71, s=-86, e=-31, w=-53 },
		['Lh']={z="Lhingris", r=4, n=-48, s=-64, e=12.1, w=2 },
		['La']={z="Lossarnach", r=3, n=-71.5, s=-80, e=-19, w=-26 },
		['Ll']={z="Lothlorien", r=2, n=-9.5, s=-19.5, e=-62, w=-74 },
		['Lo']={z="the Lone-lands", r=1, n=-28, s=-38, e=-23, w=-42 },
		['Mw']={z="Mirkwood", r=2, n=-8, s=-20, e=-41, w=-62 },
		['MM']={z="the Misty Mountains", r=1, n=-17, s=-32, e=9, w=-4 },
		['ND']={z="the North Downs", r=1, n=-4, s=-18.5, e=-33, w=-60 },
		['Sh']={z="the Shire", r=1, n=-20, s=-38, e=-63, w=-88 },
		['Sw']={z="Swanfleet", r=1, n=-50, s=-66, e=-18, w=-36 },
		['Tr']={z="the Trollshaws", r=1, n=-26, s=-44, e=-4, w=-24 },
		['TW']={z="The Wastes", r=4, n=-27, s=-41, e=2, w=-15.5 },
		['tW']={z="the Wold", r=2, n=-30, s=-47, e=-45, w=-73 },
		['Wf']={z="Westfold", r=2, n=-53.5, s=-66, e=-76.4, w=-91 },
	}
BL_Zname,BL_Zlist = {}, {}
for zc,zt in Sort(BL_Zone) do 
	BL_Zname[zt.z] = zc
	table.insert(BL_Zlist,zt.z)
end

BL_Title = { [10]="Bird-brained", [30]="Fair Fowler", [50]="Unwavering Warbler", 
			[70]="Wing-spotter", [100]="Bird-tamer" }

BL_GID = {	
	["6B916"] = {n="Orange and Blue Birding Garments",z="Swanfleet"},
	["6B920"] = {n="Orange and Mithril Birding Garments",z="Dunland"},
	["6B927"] = {n="Blue and Mithril Birding Garments",z="the Misty Mountains"},
	["6B928"] = {n="Orange and Black Birding Garments",z="Forochel"},
	["6B92A"] = {n="Blue and Gold Birding Garments",z="Ered Luin"},
	["6B92B"] = {n="Blue Birding Garments",z="Bree-land"},
	["6B92C"] = {n="Orange and Gold Birding Garments",z="Angmar"},
	["6B92E"] = {n="Blue and Black Birding Garments",z="the Trollshaws"},
	["70881"] = {n="Handful of Bird Feed",z=""},
	["709B9"] = {n="Hand-sketched Painting of Meticulous Mallards",z=""},
	["709B8"] = {n="Hand-sketched Painting of Curious Corvids",z=""},
	["709BA"] = {n="Hand-sketched Painting of a Peticular Perching",z=""},
--	["6B900"] = {n="Birder's Hat",z="The Rarest of Birds in Eriador"},
	}

BL_ID = {	
		["6E351"] = {n="Acre-gander",f={'Cl','Ew'}},
        ["7000C"] = {n="Agarnaith Gnarebill",f={'Ag'}},
		["6FF96"] = {n="Aglazor's Eagle",f={'Bf'}},
		["6FFA8"] = {n="Amroth-swan",f={'Bf'}},
		["70019"] = {n="Andros Sparrow",f={'It','La'}},
		["6E353"] = {n="Anduin Eagle",f={'Ef','Ar'}},
		["6FFBE"] = {n="Anor-hen",f={'Ar'}},
		["6BC7D"] = {n="Arantar's Tern",f={'Lo'}},
        ["6FFFC"] = {n="Argir-gull",f={'Le'}},
        ["70008"] = {n="Arnen Crossbill",f={'It'}},
		["6BB86"] = {n="Arnorian Falcon",f={'Ev'}},
		["6FFD8"] = {n="Ash-hen",f={'TW'}},
		["6BBDA"] = {n="Ashen Vulture",f={'An'}},
		["6FFF9"] = {n="Balefull Chough",f={'Ag'}},
		["6FFB7"] = {n="Bandymouse",f={'Ld'}},
		["6BB78"] = {n="Bar-tail Godwit",f={'Fo'}},
		["6BBB7"] = {n="Barleybird",f={'EL'}},
		["6E35A"] = {n="Barred Warbler",f={'Cl'}},
		["6BC82"] = {n="Barrens Shelduck",f={'An'}},
		["6BC02"] = {n="Barrow-plover",f={'Ca'}},
        ["7000E"] = {n="Beacon-owl",f={'Ar'}},
		["6BC6C"] = {n="Beleg's Shrike",f={'ND'}},
		["6E376"] = {n="Beleriand Swan",f={'Ll'}},
		["6FFE0"] = {n="Belfalas Cormorant",f={'Bf','Le'}},
		["6E343"] = {n="Bearded Moorcock",f={'Cl'}},
		["6FFC7"] = {n="Bitter Reedling",f={'Ag'}},
		["6BB63"] = {n="Black-back Gull",f={'Fo'}},
		["6E32C"] = {n="Black-headed Bunting",f={'Fg'}},
		["6BB9E"] = {n="Black-headed Gull",f={'EL','Ev'}},
		["6E314"] = {n="Black-tail Godwit",f={'Ew'}},
		["6E360"] = {n="Black-throated Diver",f={'Ew'}},
		["6E369"] = {n="Black-throated Dunnock",f={'Fg'}},
		["6FFB2"] = {n="Black-throated White-tail",f={'La'}},
		["6E37E"] = {n="Black-winged Stilt",f={'Ef'}},
		["6BBF0"] = {n="Black Kite",f={'Tr','Er'}},
		["6E34B"] = {n="Black Stork",f={'Mw'}},
		["6E327"] = {n="Black Swan",f={'GR'}},
		["6BBD1"] = {n="Blackcap",f={'MM'}},
		["6FFFB"] = {n="Blackchat",f={'Lh'}},
		["6BBD3"] = {n="Blithe Lapwing",f={'En'}},
		["6FFFD"] = {n="Bloody Dabdrake",f={'Ag'}},
		["6E361"] = {n="Blue Harrier",f={'tW'}},
        ["70017"] = {n="Blue Magpie",f={'Bf'}},
		["6E312"] = {n="Blue Thrush",f={'Cl'}},
		["6BBE1"] = {n="Blue Tit",f={'MM'}},
		["6E385"] = {n="Blue-cheeked Bee-eater",f={'Wf'}},
		["6BBF7"] = {n="Blue-tailed Robin",f={'En'}},
		["6BC1F"] = {n="Bluebill",f={'An'}},
		["6FFB3"] = {n="Bogmouse",f={'TW'}},
		["6BBF9"] = {n="Bogsnipe",f={'Du'}},
        ["7000D"] = {n="Bony Wagtail",f={'TW'}},
		["6B44B"] = {n="Brambling",f={'Sh'}},
    	["70005"] = {n="Brandur's Gull",f={'La'}},
		["6BBCC"] = {n="Brandywarbler",f={'Br'}},
		["6BBF8"] = {n="Brant",f={'An','Fo'}},
		["6BBB4"] = {n="Bree-thrush",f={'Br'}},
		["6E379"] = {n="Brego's Erne",f={'Cl'}},
		["6FFE4"] = {n="Bright Nuthatch",f={'It'}},
		["6E368"] = {n="Broadacres White-tail",f={'Ew'}},
		["6BBDE"] = {n="Bruinen Finch",f={'Tr'}},
		["6BC1B"] = {n="Bullfinch",f={'MM'}},
		["6BB69"] = {n="Butcher-shrike",f={'En'}},
		["6BBCD"] = {n="Calanor's Lark",f={'Er'}},
		["6FFC9"] = {n="Calembel Chough",f={'Ld'}},
		["6FFC0"] = {n="Cape-hen",f={'Bf'}},
		["6BBA0"] = {n="Celebrian's Bunting",f={'Tr'}},
		["6E352"] = {n="Celebrant Crossbill",f={'GR'}},
		["6B451"] = {n="Chaffinch",f={'EL','Sh'}},
		["6B43C"] = {n="Chet-woodpecker",f={'Br'}},
		["6BB7F"] = {n="Chiffchaff",f={'ND'}},
		["6FFA9"] = {n="Ciril Dunnock",f={'Bf','Ld'}},
		["6E329"] = {n="Cirion's Tern",f={'GR'}},
		["6E34E"] = {n="Cleft-plover",f={'GR','tW'}},
		["6BB6E"] = {n="Cliff Swallow",f={'EL'}},
		["6BBFC"] = {n="Cliffcreeper",f={'MM'}},
		["6E32F"] = {n="Collared Midge-catcher",f={'Fg'}},
		["6E321"] = {n="Collared Moorling",f={'tW'}},
		["6FFEE"] = {n="Cormallen Woodpecker",f={'It'}},
		["6FFD7"] = {n="Corpse-shrike",f={'TW'}},
		["6E358"] = {n="Cot-swallow",f={'Wf'}},
		["6FFBB"] = {n="Cowled Shearwater",f={'Le'}},
		["6BB88"] = {n="Crag-swallow",f={'Du'}},
		["6BB9B"] = {n="Crane",f={'Sw'}},
		["6E30C"] = {n="Crested Tit",f={'Ll','Mw'}},
		["6E344"] = {n="Croft-owl",f={'Cl'}},
		["6BC7A"] = {n="Crying Heron",f={'Ev'}},
		["6BBC3"] = {n="Cuckoo",f={'Ca'}},
		["6FFDD"] = {n="Dagorlad Plover",f={'TW'}},
		["6FFCF"] = {n="Darkling-hammer",f={'Ag'}},
		["6E365"] = {n="Deeping-dunnock",f={'Wf'}},
		["6E35F"] = {n="Dimrill Firecrest",f={'Ll'}},
		["6FFAC"] = {n="Dire Vulture",f={'Lh'}},
		["6BC16"] = {n="Dotterel",f={'ND'}},
		["6BBE0"] = {n="Down-bunting",f={'ND'}},
		["6BB70"] = {n="Drake-hunting Eagle",f={'Du'}},
		["6FFE7"] = {n="Drearhawk",f={'TW'}},
		["6FFE1"] = {n="Drossfinch",f={'Ag'}},
		["6BBF2"] = {n="Druen's Bunting",f={'Du'}},
		["6E317"] = {n="Dun Titlark",f={'Cl','Ef'}},
		["6FFE2"] = {n="Dun Whitethroat",f={'TW'}},
		["6BBD0"] = {n="Dun-crow",f={'En','Du'}},
		["6BB84"] = {n="Duncrake",f={'Du'}},
		["6BB9A"] = {n="Dunnock",f={'ND'}},
		["6FFC6"] = {n="Durthang Owl",f={'Lh'}},
		["6BBE9"] = {n="Dusk Harrier",f={'An'}},
		["6E378"] = {n="Dusk-singer",f={'Mw'}},
		["6FFF6"] = {n="Duskencap",f={'Ar','It'}},
		["6FF9A"] = {n="Dusky Ruff",f={'It'}},
		["6BB9F"] = {n="Dwarrowgander",f={'MM'}},
		["6E34C"] = {n="Eagle-owl",f={'Fg'}},
		["6BB65"] = {n="Edhel-swan",f={'Sw'}},
		["6E31A"] = {n="Egladil Woodpecker",f={'Ll'}},
		["6BB74"] = {n="Eider",f={'EL'}},
		["6E32E"] = {n="Ent Woodpecker",f={'Fg'}},
		["6E319"] = {n="Entwash Titlark",f={'Ew'}},
		["6E333"] = {n="Eohild's Warbler",f={'Ef'}},
		["6E36C"] = {n="Eorl's Warbler",f={'tW'}},
		["6FFA1"] = {n="Erech-Fowl",f={'Ld'}},
		["6BBC1"] = {n="Ereglad Woodpecker",f={'Er'}},
		["6BB79"] = {n="Eriador Jay",f={'Lo'}},
		["6E342"] = {n="Ersc-hen",f={'tW'}},
		["70009"] = {n="Erui Nuthatch",f={'La'}},
		["6BBA1"] = {n="Etelan's Stormcaller",f={'Fo'}},
		["6FF9D"] = {n="Ethir-piper",f={'La','Le'}},
		["6BC09"] = {n="Etten-tit",f={'Tr'}},
		["6BBE2"] = {n="Even-dove",f={'Ev'}},
		["6E320"] = {n="Even-hawk",f={'Mw'}},
		["6E341"] = {n="Everholt Ouzel",f={'Ef'}},
		["6BC75"] = {n="Fadrach's Fenling",f={'An'}},
		["6FFC2"] = {n="Falas Tern",f={'Bf'}},
		["6BBD8"] = {n="Falathlorn Woodpecker",f={'EL'}},
		["6E32D"] = {n="Fallow-wheep",f={'Cl'}},
        ["70002"] = {n="Fallowfinch",f={'Ld'}},
		["6E334"] = {n="Fangorn Warbler",f={'Fg'}},
		["6E33D"] = {n="Fell-crow",f={'Mw','GR'}},
		["6E35B"] = {n="Fen-strider",f={'GR'}},
		["6BBFE"] = {n="Fen-tit",f={'Sw'}},
		["6E374"] = {n="Fenmarch Piper",f={'Ef'}},
		["6BBC7"] = {n="Fir Goose",f={'Fo'}},
		["6E32B"] = {n="Fimbrethil's Firecrest",f={'Fg'}},
		["70014"] = {n="Fiend-owl",f={'Ag'}},
		["6BBEA"] = {n="Firecrest",f={'Er'}},
		["6E381"] = {n="Firien-swift",f={'Ef'}},
		["6E386"] = {n="Fladrifs's Shrike",f={'Fg'}},
		["6BB6D"] = {n="Fleet-piper",f={'Sw'}},
		["6BBC9"] = {n="Fold-warbler",f={'Du','Wf'}},
		["6BC73"] = {n="Fornost Hawk",f={'ND'}},
		["6E34D"] = {n="Fox-falcon",f={'Ew'}},
		["6FFAE"] = {n="Ghastly White-throat",f={'Ag'}},
		["6FFD0"] = {n="Giliath Lark",f={'It'}},
		["6FFDE"] = {n="Gilrain Ruff",f={'Le'}},
        ["70015"] = {n="Gladrist's Piper",f={'Bf'}},
		["6BB7D"] = {n="Gloam-singer",f={'Er'}},
		["6FFDB"] = {n="Gloomling",f={'Lh'}},
		["6BB8B"] = {n="Goldcrest",f={'ND'}},
		["6BC1C"] = {n="Golden Eagle",f={'MM'}},
		["6BBAD"] = {n="Golden Plover",f={'Ca','Lo'}},
		["6E371"] = {n="Goldensong",f={'Ll'}},
		["6BC6E"] = {n="Goldenthrush",f={'Tr'}},
		["6B445"] = {n="Goldfinch",f={'Br'}},
		["6BBED"] = {n="Goosander",f={'Ca','Sw'}},
		["6FFD6"] = {n="Gorecrest",f={'Ag'}},
		["6BB72"] = {n="Gravenwood Crossbill",f={'Du'}},
        ["70011"] = {n="Great Deck-diver",f={'Le'}},
		["70016"] = {n="Great Warbler",f={'Ld'}},
		["6B448"] = {n="Greenfinch",f={'Sh'}},
		["6BB94"] = {n="Greenshank",f={'Fo'}},
		["6BBB3"] = {n="Grey Heron",f={'Tr','Sw'}},
		["6FFED"] = {n="Grey Jay",f={'Lh','TW'}},
		["6BC26"] = {n="Grey Midge-catcher",f={'En'}},
		["6E355"] = {n="Grey Shrike",f={'Ew'}},
		["6BB8E"] = {n="Grey Wagtail",f={'Ev'}},
		["6FFEC"] = {n="Greycrest",f={'TW'}},
		["6E356"] = {n="Greydaw",f={'Wf'}},
		["6BBA4"] = {n="Greyflood Tern",f={'Ca'}},
		["6BBA9"] = {n="Greylag Goose",f={'Br'}},
        ["70001"] = {n="Greyleaf Skylark",f={'Bf'}},
		["6FFD1"] = {n="Greymouse",f={'It'}},
		["6BBE4"] = {n="Griever Owl",f={'Er'}},
		["6E318"] = {n="Guldur-shrike",f={'Mw'}},
		["6FFD2"] = {n="Hallow-starling",f={'Ar'}},
		["6E377"] = {n="Hammerbleat",f={'tW'}},
		["6BB7C"] = {n="Hang-nest Tit",f={'Er'}},
		["6FFA4"] = {n="Hangman's Crow",f={'Lh'}},
		["6E346"] = {n="Harrow-owl",f={'Ef'}},
		["6BBD4"] = {n="Harvest Bunting",f={'Lo'}},
		["6E35E"] = {n="Haunting Warbler",f={'Mw'}},
        ["7000F"] = {n="Haven-fisher",f={'Bf'}},
		["6BBA3"] = {n="Hawfinch",f={'Lo'}},
		["6FFBC"] = {n="Hawmouse",f={'Ar'}},
		["6BC7E"] = {n="Hazel-hen",f={'Tr'}},
		["6BB75"] = {n="Heath-roller",f={'Du'}},
		["6BB71"] = {n="Heather-fowl",f={'An'}},
		["6FFEF"] = {n="Hedge-singer",f={'Le'}},
		["6E33A"] = {n="Helm's Erne",f={'Wf'}},
		["6E34F"] = {n="Helmed Mew",f={'Ef','Ar'}},
		["6BB95"] = {n="Herring Gull",f={'Fo'}},
		["6E31F"] = {n="Hickamouse",f={'Ef'}},
		["6BB85"] = {n="Hithaeglir Chough",f={'MM'}},
		["6FFCC"] = {n="Hoary Wagtail",f={'Ld'}},
		["6E37A"] = {n="Holbyt-hen",f={'Cl','Ew'}},
		["6BBAC"] = {n="Holly-sparrow",f={'Er'}},
		["6E354"] = {n="Hoopoe",f={'Cl'}},
		["6E326"] = {n="Horned Dabchick",f={'Mw','GR'}},
		["6BC1A"] = {n="Horned Leaper",f={'An'}},
		["6E36F"] = {n="Hulvester",f={'Ef'}},
		["6E34A"] = {n="Hunter-falcon",f={'Wf'}},
		["6BC25"] = {n="Ice Bay Plover",f={'Fo'}},
		["6E347"] = {n="Irensaga Tern",f={'Ef'}},
		["6BBF3"] = {n="Iron Waxwing",f={'An'}},
		["6BBAE"] = {n="Isengoose",f={'Du'}},
		["6BBDB"] = {n="Isilcar's Lark",f={'Ca'}},
        ["7000B"] = {n="Isildur's Stormcaller",f={'Le'}},
        ["70013"] = {n="Ithil-jay",f={'It'}},
		["6B434"] = {n="Jackdaw",f={'Br','Lo'}},
		["6FFAA"] = {n="Keen-hawk",f={'Ar'}},
		["6E322"] = {n="Kingfisher",f={'Fg','Ll'}},
		["6BC71"] = {n="Kingsfell Blackbird",f={'ND','MM'}},
		["6BBB6"] = {n="Laeglin Warbler",f={'En'}},
		["6FFB1"] = {n="Lamedon Chiffchaff",f={'Ld'}},
		["6FFBA"] = {n="Lantriel's Shearwater",f={'Bf'}},
		["6FFA0"] = {n="Laughing Dove",f={'Ld'}},
		["6E370"] = {n="Laurel-culver",f={'Ll'}},
        ["6FFF2"] = {n="Lebennin Gannet",f={'Le','Bf'}},
		["6FFA5"] = {n="Lhaereth's Fowl",f={'Ag'}},
        ["70000"] = {n="Lhingris Gnarebill",f={'Lh'}},
		["6B449"] = {n="Linnet",f={'Sh'}},
		["6BBBA"] = {n="Lindion's Warbler",f={'Tr'}},
		["6E336"] = {n="Limlight Wagtail",f={'Fg','tW'}},
        ["70010"] = {n="Litchlark",f={'Ag'}},
		["6BC72"] = {n="Lone-hawk",f={'Lo'}},
		["6BBD9"] = {n="Long-tail Duck",f={'Ev','ND'}},
		["6BBDF"] = {n="Long-tail Tit",f={'Fo'}},
		["6BC78"] = {n="Longshanks Heron",f={'Lo'}},
		["6BB6B"] = {n="Lord-heron",f={'Sw'}},
		["6BB97"] = {n="Luin Starling",f={'EL','Ev'}},
		["6E32A"] = {n="Lurking Treecreeper",f={'Mw'}},
		["6BC0F"] = {n="Madelgard's Wagtail",f={'Sh'}},
		["6BBC0"] = {n="Magpie",f={'ND'}},
		["6E33B"] = {n="Maiden-crane",f={'Cl'}},
		["6B441"] = {n="Mallard",f={'Br'}},
		["6E348"] = {n="Mallorn-finch",f={'Ll'}},
		["6BC7C"] = {n="Marish Dabchick",f={'Sh'}},
		["6BBA8"] = {n="Marsh Warbler",f={'Sw'}},
		["6E350"] = {n="Masked Butcher-bird",f={'Wf'}},
		["6E363"] = {n="Masked Whitethroat",f={'GR'}},
		["6FF98"] = {n="Mastbreaker",f={'La'}},
		["6BB6C"] = {n="Meadow Pipit",f={'Sh'}},
		["6FFE5"] = {n="Melui-mouse",f={'La'}},
		["6BC28"] = {n="Meluinen Coot",f={'ND'}},
		["6FFDC"] = {n="Meneldil's Dunnock",f={'Ar'}},
		["6BC29"] = {n="Methedras Nightingale",f={'Du','Wf'}},
		["6BBC6"] = {n="Midgecatcher",f={'An'}},
		["6BBB2"] = {n="Midgewater Lapwing",f={'Br'}},
        ["6FFF7"] = {n="Mindon-warbler",f={'Ar'}},
		["6E313"] = {n="Mire-crake",f={'tW'}},
		["6E332"] = {n="Mirk-woodpecker",f={'Mw'}},
		["6FFDF"] = {n="Mirkhammer",f={'Lh'}},
		["6FFC4"] = {n="Mirthful Tern",f={'Le'}},
		["6BC74"] = {n="Mist-ruff",f={'Er'}},
		["6E323"] = {n="Mist-warbler",f={'Fg','Ll'}},
		["6BC27"] = {n="Mistle Thrush",f={'An'}},
		["6BBC2"] = {n="Misty Mountain Hopper",f={'MM'}},
		["6BB91"] = {n="Misty Owl",f={'MM'}},
		["6BC79"] = {n="Mitheithel Dabchick",f={'Sw'}},
        ["70012"] = {n="Moon-hawk",f={'It'}},
		["6BC6D"] = {n="Moorcock",f={'Lo'}},
		["6B450"] = {n="Moorhen",f={'Br'}},
        ["6FFAF"] = {n="Morthond Hawk",f={'Ld'}},
		["6BB80"] = {n="Mossy Pipit",f={'Er'}},
		["6E389"] = {n="Mountain Swift",f={'Fg'}},
		["6BB90"] = {n="Mourning Treecreeper",f={'Tr'}},
		["6FFCE"] = {n="Mourning-raven",f={'It'}},
		["6BBFD"] = {n="Mournshaw Bee-eater",f={'En'}},
		["6BBE3"] = {n="Narfang Shore-walker",f={'EL'}},
		["6BC11"] = {n="Naug-bittern",f={'Sw'}},
		["6BC04"] = {n="Nenuial Tern",f={'Ev'}},
		["6BB73"] = {n="Nethorn's Bunting",f={'Sw'}},
		["6E337"] = {n="Night-crown",f={'Ll','Mw'}},
		["6E372"] = {n="Night-heron",f={'Mw'}},
		["6E310"] = {n="Nightshade Bunting",f={'Mw'}},
    	["70018"] = {n="Nimrais Hawk",f={'La'}},
		["6E362"] = {n="Nimrodel's Pipit",f={'Ll'}},
		["6FFCA"] = {n="Nimrodel's Warbler",f={'Bf'}},
		["6BBBC"] = {n="North-tern",f={'Fo'}},
		["6BBCF"] = {n="Northfarthing Ninnyhammer",f={'Sh'}},
		["6BC18"] = {n="Nutcracker",f={'Tr'}},
		["6BB98"] = {n="Nuthatch",f={'MM'}},
		["6FF99"] = {n="Olive Warbler",f={'It'}},
		["6FFBD"] = {n="Ondoher's Woe",f={'TW'}},
		["6E388"] = {n="Onod-lark",f={'Fg'}},
		["6BB66"] = {n="Oranoril's Warbler",f={'Er'}},
		["6BBEB"] = {n="Orthon Drake",f={'An','Fo'}},
		["6FFD3"] = {n="Pale Dipper",f={'La'}},
		["6FF97"] = {n="Pale Midge-catcher",f={'It'}},
        ["6FFFF"] = {n="Pale Nuthatch",f={'Ld'}},
		["6BBA5"] = {n="Pale-cloaked Harrier",f={'En'}},
		["6FFAB"] = {n="Palled Wagtail",f={'Ag'}},
		["6BB67"] = {n="Peregrine Falcon",f={'MM'}},
		["6BBE5"] = {n="Perian Owl",f={'Tr'}},
		["6BBDD"] = {n="Petty-falcon",f={'Ca'}},
		["6E311"] = {n="Petty-shag",f={'GR'}},
		["6BB96"] = {n="Pine Bunting",f={'MM'}},
		["6BBB9"] = {n="Pinkfoot Goose",f={'EL'}},
		["6BB92"] = {n="Pintail",f={'An'}},
		["6BC19"] = {n="Pochard",f={'Ev','ND'}},
		["6FF9E"] = {n="Prince's Mew",f={'Bf'}},
		["6E338"] = {n="Purple Heron",f={'Ew'}},
        ["7000A"] = {n="Rattling Nightiar",f={'Lh'}},
		["6BBBD"] = {n="Red Kite",f={'Sh'}},
		["6FFE6"] = {n="Red Wryneck",f={'Ar'}},
		["6BB77"] = {n="Red-billed Chough",f={'Ev'}},
		["6BBF1"] = {n="Red-breast Robin",f={'Br','Sh'}},
		["6E37D"] = {n="Red-breasted Longnib",f={'GR'}},
		["6E33C"] = {n="Red-breasted Midge-catcher",f={'Ew'}},
		["6E37F"] = {n="Red-footed Goose",f={'GR'}},
		["6E35C"] = {n="Red-hood",f={'Fg'}},
		["6FFB5"] = {n="Red-tailed Warbler",f={'La'}},
		["6BC6B"] = {n="Red-throat Diver",f={'Fo'}},
		["6E36A"] = {n="Red-throated Pipit",f={'GR'}},
		["6BBAF"] = {n="Redcrest Drake",f={'Du'}},
		["6BBCB"] = {n="Redhorn Falcon",f={'Er'}},
		["6BBD7"] = {n="Redknot",f={'Fo'}},
		["6BB68"] = {n="Redpoll",f={'Ev'}},
		["6BBC4"] = {n="Redshank",f={'EL'}},
		["6B44D"] = {n="Redwing",f={'Br'}},
		["6BB93"] = {n="Reed Bunting",f={'Sh'}},
		["6E37B"] = {n="Reed Warbler",f={'Ew','Wf'}},
		["6BC0E"] = {n="Reedling",f={'En'}},
		["6BB8A"] = {n="Rhudaur Goose",f={'Tr'}},
		["6E373"] = {n="Rill-warbler",f={'GR','tW'}},
		["6BBBE"] = {n="Ringed Blackbird",f={'Ca'}},
		["6FFB8"] = {n="Ringlo Finch",f={'La'}},
		["6BC07"] = {n="Rivendell Woodpecker",f={'Tr'}},
		["6BC22"] = {n="River-warbler",f={'En'}},
    	["70004"] = {n="Riverswift",f={'La','Le'}},
		["6BC12"] = {n="Rock Bunting",f={'Ca'}},
		["6BC80"] = {n="Rock Dove",f={'EL'}},
		["6E375"] = {n="Rock-throstle",f={'tW'}},
		["6BC10"] = {n="Rook",f={'EL'}},
		["6BBE8"] = {n="Rose-warbler",f={'Ca'}},
		["6FF9C"] = {n="Rosy Starling",f={'La'}},
		["6FFD4"] = {n="Ruddy Jay",f={'Ld'}},
		["6E339"] = {n="Ruddy Piper",f={'tW'}},
		["6BC6F"] = {n="Ruddy Stubble-hen",f={'Ca'}},
		["6E30D"] = {n="Ruddy Shelduck",f={'Ef'}},
		["6BC03"] = {n="Ruddy Swallow",f={'En'}},
		["6E328"] = {n="Rue-dove",f={'Ll'}},
		["6FFA2"] = {n="Rush-hammer",f={'TW'}},
		["6E335"] = {n="Rushgore Bittern",f={'GR'}},
		["6BBBB"] = {n="Rushock-snipe",f={'Sh'}},
		["6E330"] = {n="Rust Swallow",f={'Fg','tW'}},
		["6FFA3"] = {n="Rust-tit",f={'Le'}},
		["6BB81"] = {n="Scoter",f={'Fo'}},
		["6FFC3"] = {n="Scrub Ruddock",f={'Ag'}},
		["6BB7E"] = {n="Sedge Warbler",f={'Ca'}},
		["6E366"] = {n="Sedge-shear",f={'Cl'}},
		["6E316"] = {n="Shadowy Redstart",f={'Mw'}},
		["6FFCD"] = {n="Shade-owl",f={'TW'}},
		["6BBA2"] = {n="Shaw-coot",f={'Tr','Sw'}},
		["6FFE9"] = {n="Sheen-owl",f={'La'}},
		["6E36D"] = {n="Shovel-heron",f={'GR'}},
		["6BB6F"] = {n="Shoveler",f={'Lo'}},
		["6FFE3"] = {n="Shrouded Crow",f={'TW'}},
		["6BBEF"] = {n="Shrouded Drake",f={'An'}},
		["6BBAB"] = {n="Sickle Curlew",f={'Ev'}},
		["6E35D"] = {n="Sickle-bill",f={'Ew'}},
		["6E30F"] = {n="Silver Easterfowl",f={'Cl','Ef'}},
		["6BBBF"] = {n="Silver Stork",f={'Sw'}},
		["6E345"] = {n="Silver-gander",f={'Wf'}},
        ["6FFF3"] = {n="Silvertail",f={'Ar'}},
		["6BC13"] = {n="Silvertine Harrier",f={'Er'}},
		["6E384"] = {n="Silvertine Stonechat",f={'Ll'}},
        ["70006"] = {n="Sirith-stint",f={'Le'}},
		["6B436"] = {n="Skylark",f={'Br'}},
		["6FFEB"] = {n="Slaughter-kite",f={'Ag'}},
		["6B43D"] = {n="Smial-martin",f={'Sh'}},
		["6BBEC"] = {n="Snow-kite",f={'Fo'}},
        ["6FFF4"] = {n="Snow-sparrow",f={'Ld'}},
		["6E364"] = {n="Snowbourn Piper",f={'Cl'}},
		["6BB6A"] = {n="Solemn Tit",f={'Lo'}},
		["6E357"] = {n="Sombre-lark",f={'Mw'}},
		["6FFF1"] = {n="Sombre Tit",f={'Lh'}},
		["6BB62"] = {n="Song Thrush",f={'MM','ND'}},
		["6B44F"] = {n="Sparrowhawk",f={'Br'}},
		["6E367"] = {n="Spear-hen",f={'Cl'}},
		["6E359"] = {n="Speckled Bluethroat",f={'Ef'}},
		["6FFB4"] = {n="Speckled Owl",f={'Ld'}},
		["6FFE8"] = {n="Spider-lark",f={'Lh'}},
		["6FFF5"] = {n="Spinetail",f={'Lh'}},
		["6E340"] = {n="Spotted Cuckoo",f={'Fg'}},
		["6BB99"] = {n="Spotted Redshank",f={'ND'}},
		["6E349"] = {n="Spurred Lapwing",f={'tW'}},
		["6E331"] = {n="Spurred Titlark",f={'Ef'}},
		["6FFF8"] = {n="Stained Ruff",f={'Ag'}},
		["6BBB1"] = {n="Starkmoor Owl",f={'Du'}},
		["6BC0D"] = {n="Stock Dove",f={'ND'}},
		["6E315"] = {n="Stone Pipit",f={'tW'}},
		["6BBD6"] = {n="Stonechat",f={'Lo'}},
		["6E33F"] = {n="Stonedeans Redpoll",f={'Wf'}},
		["6FFB9"] = {n="Stonescraper",f={'TW'}},
		["6BC15"] = {n="Stonevale Goshawk",f={'Du'}},
		["6BB9D"] = {n="Stoor-crake",f={'Sw'}},
		["6FF9B"] = {n="Streaked Swallow",f={'Lh','TW'}},
		["6BC7F"] = {n="Striding Ruff",f={'Br'}},
		["6FFEA"] = {n="Sunfinch",f={'Ar'}},
		["6BC14"] = {n="Swallow",f={'Ca','Lo'}},
		["6FFA7"] = {n="Swallow-plover",f={'Bf'}},
		["6BC77"] = {n="Swart-hen",f={'Du'}},
		["6E36B"] = {n="Sweet-minstrel",f={'Ll'}},
        ["70007"] = {n="Sweetlark",f={'Ar'}},
		["6FFAD"] = {n="Swelldrake",f={'Bf','Ld'}},
		["6B444"] = {n="Swift",f={'Br','Lo'}},
		["6FFDA"] = {n="Tarlang's Woodpecker",f={'Ld'}},
		["6BBB0"] = {n="Tawny Owl",f={'EL'}},
		["6B443"] = {n="Teal",f={'EL','Sh'}},
		["6BC05"] = {n="Thick-knee",f={'Lo'}},
		["6FFFE"] = {n="Thistling",f={'It','La'}},
		["6E33E"] = {n="Thrihyrne Vulture",f={'Wf'}},
		["6E30E"] = {n="Tinuviel's Nightingale",f={'Ll'}},
		["6FFC1"] = {n="Tufted Drake",f={'Ar','It'}},
		["6FFB0"] = {n="Tumladen Jay",f={'La'}},
		["6BBF6"] = {n="Turtle-dove",f={'Ca'}},
		["6BBCA"] = {n="Twite",f={'En','Er'}},
		["6E382"] = {n="Undeep-stint",f={'tW'}},
		["6BB89"] = {n="Valardis's Swan",f={'Ev'}},
		["6FFBF"] = {n="Veiled Nightingale",f={'Lh'}},
		["6BC70"] = {n="Wadewater Heron",f={'Sw'}},
		["6FFB6"] = {n="Wailing Warbler",f={'Lh'}},
		["6E324"] = {n="Waled Midge-catcher",f={'Cl'}},
		["6FFD9"] = {n="Wallow-warbler",f={'Ag'}},
		["6FFA6"] = {n="Wan-swift",f={'Ar'}},
		["6FFFA"] = {n="Warden-owl",f={'It'}},
		["6BBC5"] = {n="Water Pipit",f={'Ca','Sw'}},
		["6BBD2"] = {n="Water Rail",f={'Ev'}},
		["6BB8F"] = {n="Weatherdrake",f={'Lo'}},
		["6FFF0"] = {n="Weeping Crane",f={'TW'}},
		["6BC7B"] = {n="Weeping Diver",f={'An'}},
		["6BC20"] = {n="Weeping Finch",f={'An'}},
		["6E31B"] = {n="Weeping Owl",f={'Ll'}},
		["6E31E"] = {n="Westfold Eddish-hen",f={'Wf'}},
		["6BBEE"] = {n="Wheatear",f={'EL'}},
		["6FFC8"] = {n="Whimbrel",f={'Le'}},
		["6BBE7"] = {n="Whinchat",f={'MM'}},
		["6BBB8"] = {n="White Piper",f={'Ev'}},
		["6BB7A"] = {n="White-eye Duck",f={'En','Er'}},
		["6FF9F"] = {n="White-rumped Ruddock",f={'Le'}},
		["6BC17"] = {n="White-tailed Eagle",f={'EL'}},
		["6BBE6"] = {n="White-throated Dipper",f={'Ev'}},
		["6E31D"] = {n="White-winged Tern",f={'Ew'}},
		["6BB8D"] = {n="Whitethroat",f={'ND'}},
		["6E383"] = {n="Whither-warbler",f={'Wf'}},
		["6E31C"] = {n="Wilder-hammer",f={'tW'}},
		["6E387"] = {n="Willow Warbler",f={'Ew'}},
		["6BC76"] = {n="Willow-fowl",f={'Fo'}},
		["6FFCB"] = {n="Wind-beater",f={'Le'}},
		["6BBD5"] = {n="Windfell Owl",f={'En'}},
		["6E380"] = {n="Withy-mouse",f={'Ew','Wf'}},
		["6E36E"] = {n="Wood Piper",f={'Ew'}},
		["6B44C"] = {n="Wood-pigeon",f={'Br','Sh'}},
		["6BB64"] = {n="Woodlark",f={'Tr'}},
		["6BBDC"] = {n="Woodsnipe",f={'Ca'}},
		["6E325"] = {n="Wraith-owl",f={'Mw'}},
		["6BC21"] = {n="Wren",f={'MM'}},
		["6FFC5"] = {n="Writhen-wren",f={'Lh'}},
		["6BC23"] = {n="Wryneck",f={'En'}},
		["6BC81"] = {n="Yale-sparrow",f={'Sh'}},
		["6BC24"] = {n="Yellow Wagtail",f={'En','Du'}},
		["6E37C"] = {n="Yellow-billed Diver",f={'GR'}},
		["6B440"] = {n="Yellowhammer",f={'Tr','Er'}},
	}
BL_Bname = {}
for z,t in pairs(BL_Zone) do t.id = {} end
for id,t in pairs(BL_ID) do
	BL_Bname[t.n] = id
	for i,z in pairs(t.f) do
		local zt = BL_Zone[z]
		if not zt then Turbine.Shell.WriteLine("Bad zone code: "..z)
		else zt.id[id] = true end
	end
end