-- Birding Log - French localisation overlay
-- Added by Dusk FR patch. Internal English keys are intentionally preserved.

local ZoneFR = {
    Ag="Agarnaith", An="Angmar", Ar="Anórien", Bf="Belfalas",
    Br="Pays de Bree", Ca="Cardolan", Cl="Les Crofts", Du="Pays de Dun",
    Ef="Estfolde", En="Enedwaith", EL="Ered Luin", Er="Eregion",
    Ev="Evendim", Ew="L'Entalluve", Fg="Fangorn", Fo="Forochel",
    GR="Grand Fleuve", It="Ithilien", Ld="Lamedon", Le="Lebennin",
    Lh="Lhingris", La="Lossarnach", Ll="Lothlórien", Lo="Terres Solitaires",
    MM="Monts Brumeux", Mw="Forêt Noire", ND="Hauts du Nord", Sh="Comté",
    Sw="Les Noues des cygnes", Tr="Trouée des Trolls", tW="Plateau",
    TW="Les Landes désertiques", Wf="Ouestfolde"
}

-- Display aliases: keep the original Zone[z].z for internal comparisons.
BL_Zlist = {}
for zc,zt in Sort(BL_Zone) do
    zt.ln = ZoneFR[zc] or zt.z
    BL_Zname[zt.ln] = zc
    table.insert(BL_Zlist,zt.ln)
end

-- FR6: 470/470 noms d’oiseaux officiels + 13 objets liés au hobby préchargés.
-- Source: tables de localisation FR du client LOTRO, croisées par ID interne.
local NamesFR = {
    ["6B434"] = "Jacquot", -- Jackdaw
    ["6B436"] = "Alouette", -- Skylark
    ["6B43C"] = "Pivert du Bois de Chet", -- Chet-woodpecker
    ["6B43D"] = "Martinet des smials", -- Smial-martin
    ["6B440"] = "Bruant jaune", -- Yellowhammer
    ["6B441"] = "Colvert", -- Mallard
    ["6B443"] = "Sarcelle", -- Teal
    ["6B444"] = "Martinet", -- Swift
    ["6B445"] = "Chardonneret élégant", -- Goldfinch
    ["6B448"] = "Verdier", -- Greenfinch
    ["6B449"] = "Linotte", -- Linnet
    ["6B44B"] = "Pinson du Nord", -- Brambling
    ["6B44C"] = "Pigeon ramier", -- Wood-pigeon
    ["6B44D"] = "Grive mauvis", -- Redwing
    ["6B44F"] = "Épervier", -- Sparrowhawk
    ["6B450"] = "Gallinule", -- Moorhen
    ["6B451"] = "Pinson des arbres", -- Chaffinch
    ["6B900"] = "Chapeau d'ornithologue", -- Birder's Hat
    ["6B916"] = "Tenue d'ornithologie orange et bleu", -- Orange and Blue Birding Garments
    ["6B920"] = "Tenue d'ornithologie orange et mithril", -- Orange and Mithril Birding Garments
    ["6B927"] = "Tenue d'ornithologie bleu et mithril", -- Blue and Mithril Birding Garments
    ["6B928"] = "Tenue d'ornithologie orange et noir", -- Orange and Black Birding Garments
    ["6B92A"] = "Tenue d'ornithologie bleu et doré", -- Blue and Gold Birding Garments
    ["6B92B"] = "Tenue d'ornithologie bleue", -- Blue Birding Garments
    ["6B92C"] = "Tenue d'ornithologie orange et doré", -- Orange and Gold Birding Garments
    ["6B92E"] = "Tenue d'ornithologie bleu et noir", -- Blue and Black Birding Garments
    ["6BB62"] = "Grive cantatrice", -- Song Thrush
    ["6BB63"] = "Mouette à dos noir", -- Black-back Gull
    ["6BB64"] = "Alouette lulu", -- Woodlark
    ["6BB65"] = "Cygne d'Edhel", -- Edhel-swan
    ["6BB66"] = "Fauvette d'Oranoril", -- Oranoril's Warbler
    ["6BB67"] = "Faucon pèlerin", -- Peregrine Falcon
    ["6BB68"] = "Sizerin flammé", -- Redpoll
    ["6BB69"] = "Pie grièche massacreuse", -- Butcher-shrike
    ["6BB6A"] = "Mésange charbonnière", -- Solemn Tit
    ["6BB6B"] = "Seigneur héron", -- Lord-heron
    ["6BB6C"] = "Pipit farlouse", -- Meadow Pipit
    ["6BB6D"] = "Bécasseau de la flotte", -- Fleet-piper
    ["6BB6E"] = "Hirondelle des falaises", -- Cliff Swallow
    ["6BB6F"] = "Canard souchet", -- Shoveler
    ["6BB70"] = "Aigle chasseur de drakes", -- Drake-hunting Eagle
    ["6BB71"] = "Poule de bruyère", -- Heather-fowl
    ["6BB72"] = "Bec-croisé de Boisouvré", -- Gravenwood Crossbill
    ["6BB73"] = "Bruant de Nethorn", -- Nethorn's Bunting
    ["6BB74"] = "Eider", -- Eider
    ["6BB75"] = "Rollier de bruyère", -- Heath-roller
    ["6BB77"] = "Chocard à bec rouge", -- Red-billed Chough
    ["6BB78"] = "Barge à queue striée", -- Bar-tail Godwit
    ["6BB79"] = "Geai d'Eriador", -- Eriador Jay
    ["6BB7A"] = "Fuligule nyroca", -- White-eye Duck
    ["6BB7C"] = "Mésange à nid suspendu", -- Hang-nest Tit
    ["6BB7D"] = "Cantateur du crépuscule", -- Gloam-singer
    ["6BB7E"] = "Phragmite des joncs", -- Sedge Warbler
    ["6BB7F"] = "Pouillot véloce", -- Chiffchaff
    ["6BB80"] = "Pipit moussu", -- Mossy Pipit
    ["6BB81"] = "Macreuse", -- Scoter
    ["6BB84"] = "Marouette de Dun", -- Duncrake
    ["6BB85"] = "Chocard d'Hithaeglir", -- Hithaeglir Chough
    ["6BB86"] = "Faucon d'Arnor", -- Arnorian Falcon
    ["6BB88"] = "Hirondelle des rochers", -- Crag-swallow
    ["6BB89"] = "Cygne de Valardis", -- Valardis's Swan
    ["6BB8A"] = "Oie du Rhudaur", -- Rhudaur Goose
    ["6BB8B"] = "Roitelet huppé", -- Goldcrest
    ["6BB8D"] = "Fauvette grisette", -- Whitethroat
    ["6BB8E"] = "Bergeronnette grise", -- Grey Wagtail
    ["6BB8F"] = "Colvert", -- Weatherdrake
    ["6BB90"] = "Grimpereau des bois endeuillé", -- Mourning Treecreeper
    ["6BB91"] = "Chouette brumeuse", -- Misty Owl
    ["6BB92"] = "Canard pilet", -- Pintail
    ["6BB93"] = "Bruant des roseaux", -- Reed Bunting
    ["6BB94"] = "Chevalier aboyeur", -- Greenshank
    ["6BB95"] = "Goéland argenté", -- Herring Gull
    ["6BB96"] = "Bruant des pins", -- Pine Bunting
    ["6BB97"] = "Étourneau de Luin", -- Luin Starling
    ["6BB98"] = "Sittelle", -- Nuthatch
    ["6BB99"] = "Chevalier arlequin", -- Spotted Redshank
    ["6BB9A"] = "Accenteur mouchet", -- Dunnock
    ["6BB9B"] = "Grue", -- Crane
    ["6BB9D"] = "Marouette des Forts", -- Stoor-crake
    ["6BB9E"] = "Mouette à tête noire", -- Black-headed Gull
    ["6BB9F"] = "Jars de Dwarrow", -- Dwarrowgander
    ["6BBA0"] = "Bruant de Celebrian", -- Celebrian's Bunting
    ["6BBA1"] = "Appel-tempête d'Etelan", -- Etelan's Stormcaller
    ["6BBA2"] = "Foulque de trouée", -- Shaw-coot
    ["6BBA3"] = "Gros-bec casse-noyaux", -- Hawfinch
    ["6BBA4"] = "Sterne du Flot Gris", -- Greyflood Tern
    ["6BBA5"] = "Persécuteur à robe pâle", -- Pale-cloaked Harrier
    ["6BBA8"] = "Rousserolle Verderolle", -- Marsh Warbler
    ["6BBA9"] = "Oie cendrée", -- Greylag Goose
    ["6BBAB"] = "Courlis cendré falciforme", -- Sickle Curlew
    ["6BBAC"] = "Moineau des houx", -- Holly-sparrow
    ["6BBAD"] = "Gravelot rouge", -- Golden Plover
    ["6BBAE"] = "Isenoie", -- Isengoose
    ["6BBAF"] = "Drake à crête rouge", -- Redcrest Drake
    ["6BBB0"] = "Chouette hulotte", -- Tawny Owl
    ["6BBB1"] = "Hibou d'Apreterre", -- Starkmoor Owl
    ["6BBB2"] = "Vanneau huppé de l'Eau-aux-cousins", -- Midgewater Lapwing
    ["6BBB3"] = "Héron Gris", -- Grey Heron
    ["6BBB4"] = "Grive de Bree", -- Bree-thrush
    ["6BBB6"] = "Fauvette de Laeglin", -- Laeglin Warbler
    ["6BBB7"] = "Bergeronnette printanière", -- Barleybird
    ["6BBB8"] = "Bécasseau blanc", -- White Piper
    ["6BBB9"] = "Oie à pattes roses", -- Pinkfoot Goose
    ["6BBBA"] = "Fauvette de Lindion", -- Lindion's Warbler
    ["6BBBB"] = "Bécassine de Rushock", -- Rushock-snipe
    ["6BBBC"] = "Sterne du nord", -- North-tern
    ["6BBBD"] = "Milan royal", -- Red Kite
    ["6BBBE"] = "Merle annelé", -- Ringed Blackbird
    ["6BBBF"] = "Cigogne argentée", -- Silver Stork
    ["6BBC0"] = "Pie", -- Magpie
    ["6BBC1"] = "Pivert d'Ereglad", -- Ereglad Woodpecker
    ["6BBC2"] = "Sauteur des Monts Brumeux", -- Misty Mountain Hopper
    ["6BBC3"] = "Coucou", -- Cuckoo
    ["6BBC4"] = "Chevalier gambette", -- Redshank
    ["6BBC5"] = "Pipit spioncelle", -- Water Pipit
    ["6BBC6"] = "Attrape-moucheron", -- Midgecatcher
    ["6BBC7"] = "Oie des pins", -- Fir Goose
    ["6BBC9"] = "Fauvette des parcs", -- Fold-warbler
    ["6BBCA"] = "Linotte à bec jaune", -- Twite
    ["6BBCB"] = "Faucon de Rubicorne", -- Redhorn Falcon
    ["6BBCC"] = "Fauvette du Brandevin", -- Brandywarbler
    ["6BBCD"] = "Alouette de Calanor", -- Calanor's Lark
    ["6BBCF"] = "Coucou du Quartier du Nord", -- Northfarthing Ninnyhammer
    ["6BBD0"] = "Corbeau de Dun", -- Dun-crow
    ["6BBD1"] = "Fauvette à tête noire", -- Blackcap
    ["6BBD2"] = "Râle d'eau", -- Water Rail
    ["6BBD3"] = "Vanneau huppé amical", -- Blithe Lapwing
    ["6BBD4"] = "Bruant des moissons", -- Harvest Bunting
    ["6BBD5"] = "Hibou des Chutebrises", -- Windfell Owl
    ["6BBD6"] = "Tarier pâtre", -- Stonechat
    ["6BBD7"] = "Nœud rouge", -- Redknot
    ["6BBD8"] = "Pivert de Falathlorn", -- Falathlorn Woodpecker
    ["6BBD9"] = "Canard à longue queue", -- Long-tail Duck
    ["6BBDA"] = "Vautour cendré", -- Ashen Vulture
    ["6BBDB"] = "Alouette d'Isilcar", -- Isilcar's Lark
    ["6BBDC"] = "Bécassine des bois", -- Woodsnipe
    ["6BBDD"] = "Faucon mesquin", -- Petty-falcon
    ["6BBDE"] = "Chardonneret du Bruinen", -- Bruinen Finch
    ["6BBDF"] = "Mésange à longue queue", -- Long-tail Tit
    ["6BBE0"] = "Bruant des dunes", -- Down-bunting
    ["6BBE1"] = "Mésange bleue", -- Blue Tit
    ["6BBE2"] = "Colombeven", -- Even-dove
    ["6BBE3"] = "Arpenteur de rive de Narfang", -- Narfang Shore-walker
    ["6BBE4"] = "Chouette griffeuse", -- Griever Owl
    ["6BBE5"] = "Chouette de Perian", -- Perian Owl
    ["6BBE6"] = "Cincle plongeur", -- White-throated Dipper
    ["6BBE7"] = "Tarier des prés", -- Whinchat
    ["6BBE8"] = "Paruline des roses", -- Rose-warbler
    ["6BBE9"] = "Busard crépusculaire", -- Dusk Harrier
    ["6BBEA"] = "Roitelet à triple bandeau", -- Firecrest
    ["6BBEB"] = "Drake d'Orthon", -- Orthon Drake
    ["6BBEC"] = "Milan blanc", -- Snow-kite
    ["6BBED"] = "Grand harle", -- Goosander
    ["6BBEE"] = "Traquet motteux", -- Wheatear
    ["6BBEF"] = "Drake enténébré", -- Shrouded Drake
    ["6BBF0"] = "Milan noir", -- Black Kite
    ["6BBF1"] = "Rouge-gorge", -- Red-breast Robin
    ["6BBF2"] = "Bruant de Druen", -- Druen's Bunting
    ["6BBF3"] = "Jaseur de fer", -- Iron Waxwing
    ["6BBF6"] = "Tourterelle des bois", -- Turtle-dove
    ["6BBF7"] = "Rouge-gorge à queue bleue", -- Blue-tailed Robin
    ["6BBF8"] = "Bernache cravant", -- Brant
    ["6BBF9"] = "Bécassine des marais", -- Bogsnipe
    ["6BBFC"] = "Grimpefalaise", -- Cliffcreeper
    ["6BBFD"] = "Guêpier de Tristebois", -- Mournshaw Bee-eater
    ["6BBFE"] = "Mésange des fagnes", -- Fen-tit
    ["6BC02"] = "Pluvier des galgals", -- Barrow-plover
    ["6BC03"] = "Hirondelle vermeille", -- Ruddy Swallow
    ["6BC04"] = "Sterne de Nenuial", -- Nenuial Tern
    ["6BC05"] = "Œdicnème", -- Thick-knee
    ["6BC07"] = "Pic de Fondcombe", -- Rivendell Woodpecker
    ["6BC09"] = "Mésange d'Etten", -- Etten-tit
    ["6BC0D"] = "Pigeon colombin", -- Stock Dove
    ["6BC0E"] = "Semis", -- Reedling
    ["6BC0F"] = "Bergeronnette de Madelgard", -- Madelgard's Wagtail
    ["6BC10"] = "Rouque", -- Rook
    ["6BC11"] = "Butor de Naug", -- Naug-bittern
    ["6BC12"] = "Bruant fou", -- Rock Bunting
    ["6BC13"] = "Busard de la Corne d'Argent", -- Silvertine Harrier
    ["6BC14"] = "Hirondelle", -- Swallow
    ["6BC15"] = "Autour des palombes", -- Stonevale Goshawk
    ["6BC16"] = "Pluvier", -- Dotterel
    ["6BC17"] = "Pygargue à queue blanche", -- White-tailed Eagle
    ["6BC18"] = "Cassenoix moucheté", -- Nutcracker
    ["6BC19"] = "Nette rousse", -- Pochard
    ["6BC1A"] = "Sauteur cornu", -- Horned Leaper
    ["6BC1B"] = "Bouvreuil pivoine", -- Bullfinch
    ["6BC1C"] = "Aigle royal", -- Golden Eagle
    ["6BC1F"] = "Canard à bec bleu", -- Bluebill
    ["6BC20"] = "Roselin pleureur", -- Weeping Finch
    ["6BC21"] = "Troglodyte", -- Wren
    ["6BC22"] = "Locustelle fluviatile", -- River-warbler
    ["6BC23"] = "Torcol", -- Wryneck
    ["6BC24"] = "Bergeronnette jaune", -- Yellow Wagtail
    ["6BC25"] = "Gravelot de la Baie de Forochel", -- Ice Bay Plover
    ["6BC26"] = "Attrape-moucheron gris", -- Grey Midge-catcher
    ["6BC27"] = "Grive draine", -- Mistle Thrush
    ["6BC28"] = "Foulque de Meluinen", -- Meluinen Coot
    ["6BC29"] = "Rossignol de Methedras", -- Methedras Nightingale
    ["6BC6B"] = "Plongeur à gorge rouge", -- Red-throat Diver
    ["6BC6C"] = "Pie-grièche de Beleg", -- Beleg's Shrike
    ["6BC6D"] = "Coq des landes", -- Moorcock
    ["6BC6E"] = "Grive dorée", -- Goldenthrush
    ["6BC6F"] = "Poule barbue vermeille", -- Ruddy Stubble-hen
    ["6BC70"] = "Héron du Guédeau", -- Wadewater Heron
    ["6BC71"] = "Merle noir de la Lande du Roi", -- Kingsfell Blackbird
    ["6BC72"] = "Faucon solitaire", -- Lone-hawk
    ["6BC73"] = "Faucon de Fornost", -- Fornost Hawk
    ["6BC74"] = "Collerette de brume", -- Mist-ruff
    ["6BC75"] = "Fagnelet de Fadrach", -- Fadrach's Fenling
    ["6BC76"] = "Lagopède des saules", -- Willow-fowl
    ["6BC77"] = "Poule noire", -- Swart-hen
    ["6BC78"] = "Héron longuepattes", -- Longshanks Heron
    ["6BC79"] = "Petit grèbe de Mitheithel", -- Mitheithel Dabchick
    ["6BC7A"] = "Héron pleureur", -- Crying Heron
    ["6BC7B"] = "Plongeon huard pleureur", -- Weeping Diver
    ["6BC7C"] = "Petit grèbe des marais", -- Marish Dabchick
    ["6BC7D"] = "Sterne d'Arantar", -- Arantar's Tern
    ["6BC7E"] = "Gélinotte des bois", -- Hazel-hen
    ["6BC7F"] = "Combattant varié", -- Striding Ruff
    ["6BC80"] = "Pigeon biset", -- Rock Dove
    ["6BC81"] = "Moineau du Yale", -- Yale-sparrow
    ["6BC82"] = "Tadorne des landes", -- Barrens Shelduck
    ["6E30C"] = "Mésange huppée", -- Crested Tit
    ["6E30D"] = "Canard vermeille", -- Ruddy Shelduck
    ["6E30E"] = "Rossignol de Tinuviel", -- Tinuviel's Nightingale
    ["6E30F"] = "Sauvagine argentée", -- Silver Easterfowl
    ["6E310"] = "Bruant de l'obscurité", -- Nightshade Bunting
    ["6E311"] = "Cormorant", -- Petty-shag
    ["6E312"] = "Grive bleue", -- Blue Thrush
    ["6E313"] = "Échassier des marais", -- Mire-crake
    ["6E314"] = "Barge à queue noire", -- Black-tail Godwit
    ["6E315"] = "Pipit des roches", -- Stone Pipit
    ["6E316"] = "Rougequeue des ombres", -- Shadowy Redstart
    ["6E317"] = "Pipit de Dun", -- Dun Titlark
    ["6E318"] = "Pie-grièche de Guldur", -- Guldur-shrike
    ["6E319"] = "Pipit de l'Entalluve", -- Entwash Titlark
    ["6E31A"] = "Pivert d'Egladil", -- Egladil Woodpecker
    ["6E31B"] = "Hibou pleureur", -- Weeping Owl
    ["6E31C"] = "Pic sauvage", -- Wilder-hammer
    ["6E31D"] = "Sterne à aile blanche", -- White-winged Tern
    ["6E31E"] = "Poule d'Ouestfolde", -- Westfold Eddish-hen
    ["6E31F"] = "Mésange bleue", -- Hickamouse
    ["6E320"] = "Faucon vespéral", -- Even-hawk
    ["6E321"] = "Oiseau des landes à collerette", -- Collared Moorling
    ["6E322"] = "Martin-pêcheur", -- Kingfisher
    ["6E323"] = "Fauvette de brume", -- Mist-warbler
    ["6E324"] = "Attrape-moucheron plat", -- Waled Midge-catcher
    ["6E325"] = "Hibou spectral", -- Wraith-owl
    ["6E326"] = "Petit grèbe à corne", -- Horned Dabchick
    ["6E327"] = "Cygne noir", -- Black Swan
    ["6E328"] = "Colombe chagrinée", -- Rue-dove
    ["6E329"] = "Sterne de Cirion", -- Cirion's Tern
    ["6E32A"] = "Grimpereau des bois caché", -- Lurking Treecreeper
    ["6E32B"] = "Roitelet de Fimbrethil", -- Fimbrethil's Firecrest
    ["6E32C"] = "Bruant à tête noire", -- Black-headed Bunting
    ["6E32D"] = "Poule agricole", -- Fallow-wheep
    ["6E32E"] = "Pivert de la Forêt d'Ent", -- Ent Woodpecker
    ["6E32F"] = "Attrape-moucheron à collerette", -- Collared Midge-catcher
    ["6E330"] = "Hirondelle cuivrée", -- Rust Swallow
    ["6E331"] = "Pipit à éperons", -- Spurred Titlark
    ["6E332"] = "Pivert des marais", -- Mirk-woodpecker
    ["6E333"] = "Fauvette d'Eohild", -- Eohild's Warbler
    ["6E334"] = "Fauvette de Fangorn", -- Fangorn Warbler
    ["6E335"] = "Butor du Rushgore", -- Rushgore Bittern
    ["6E336"] = "Bergeronnette de Limeclair", -- Limlight Wagtail
    ["6E337"] = "Crête nocture", -- Night-crown
    ["6E338"] = "Héron violet", -- Purple Heron
    ["6E339"] = "Bécasseau vermeille", -- Ruddy Piper
    ["6E33A"] = "Pygargue de Helm", -- Helm's Erne
    ["6E33B"] = "Grue demoiselle", -- Maiden-crane
    ["6E33C"] = "Attrape-moucheron à ventre rouge", -- Red-breasted Midge-catcher
    ["6E33D"] = "Corbeau noir", -- Fell-crow
    ["6E33E"] = "Vautour de Thrihyrne", -- Thrihyrne Vulture
    ["6E33F"] = "Sizerin de Pierreval", -- Stonedeans Redpoll
    ["6E340"] = "Coucou moucheté", -- Spotted Cuckoo
    ["6E341"] = "Merle de l'Everholt", -- Everholt Ouzel
    ["6E342"] = "Caille", -- Ersc-hen
    ["6E343"] = "Coq des landes barbu", -- Bearded Moorcock
    ["6E344"] = "Hibou agricole", -- Croft-owl
    ["6E345"] = "Oie argentée", -- Silver-gander
    ["6E346"] = "Hibou-creuseur", -- Harrow-owl
    ["6E347"] = "Estorlet d'Irensaga", -- Irensaga Tern
    ["6E348"] = "Pinson des mallornes", -- Mallorn-finch
    ["6E349"] = "Vanneau à éperons", -- Spurred Lapwing
    ["6E34A"] = "Faucon-chasseur", -- Hunter-falcon
    ["6E34B"] = "Cigogne noire", -- Black Stork
    ["6E34C"] = "Hibou grand-duc", -- Eagle-owl
    ["6E34D"] = "Faucon renard", -- Fox-falcon
    ["6E34E"] = "Gravelot des falaises", -- Cleft-plover
    ["6E34F"] = "Mouette casquée", -- Helmed Mew
    ["6E350"] = "Cassican masqué", -- Masked Butcher-bird
    ["6E351"] = "Oie des terres", -- Acre-gander
    ["6E352"] = "Bec-croisé du Celebrant", -- Celebrant Crossbill
    ["6E353"] = "Aigle de l'Anduin", -- Anduin Eagle
    ["6E354"] = "Huppe", -- Hoopoe
    ["6E355"] = "Pie-grièche grise", -- Grey Shrike
    ["6E356"] = "Corneille grise", -- Greydaw
    ["6E357"] = "Alouette sombre", -- Sombre-lark
    ["6E358"] = "Hirondelle de maison", -- Cot-swallow
    ["6E359"] = "Gorgebleue moucheté", -- Speckled Bluethroat
    ["6E35A"] = "Fauvette épervière", -- Barred Warbler
    ["6E35B"] = "Huppe des fougères", -- Fen-strider
    ["6E35C"] = "Passereau rouge", -- Red-hood
    ["6E35D"] = "Paradisier", -- Sickle-bill
    ["6E35E"] = "Fauvette envoûtante", -- Haunting Warbler
    ["6E35F"] = "Roitelet des Rigoles Sombres", -- Dimrill Firecrest
    ["6E360"] = "Plongeur à gorge noire", -- Black-throated Diver
    ["6E361"] = "Busard bleu", -- Blue Harrier
    ["6E362"] = "Pipit de Nimrodel", -- Nimrodel's Pipit
    ["6E363"] = "Fauvette grisette masquée", -- Masked Whitethroat
    ["6E364"] = "Bécasseau de Neigebronne", -- Snowbourn Piper
    ["6E365"] = "Accenteur des hauteurs", -- Deeping-dunnock
    ["6E366"] = "Puffin des joncs", -- Sedge-shear
    ["6E367"] = "Poule à queue pointue", -- Spear-hen
    ["6E368"] = "Queue-blanche des Grands-arpents", -- Broadacres White-tail
    ["6E369"] = "Accenteur mouchet à gorge noire", -- Black-throated Dunnock
    ["6E36A"] = "Pipit à gorge rouge", -- Red-throated Pipit
    ["6E36B"] = "Ménestrel doux", -- Sweet-minstrel
    ["6E36C"] = "Fauvette d'Eorl", -- Eorl's Warbler
    ["6E36D"] = "Héron spatule", -- Shovel-heron
    ["6E36E"] = "Pinson sylvestre", -- Wood Piper
    ["6E36F"] = "Hulcolteur", -- Hulvester
    ["6E370"] = "Colbert-laurier", -- Laurel-culver
    ["6E371"] = "Chandor", -- Goldensong
    ["6E372"] = "Bihoreau", -- Night-heron
    ["6E373"] = "Fauvette des ruisseaux", -- Rill-warbler
    ["6E374"] = "Bécasseau de la Fenmarche", -- Fenmarch Piper
    ["6E375"] = "Grive des rochers", -- Rock-throstle
    ["6E376"] = "Cygne du Beleriand", -- Beleriand Swan
    ["6E377"] = "Bécassine-marteau", -- Hammerbleat
    ["6E378"] = "Cantateur crépusculaire", -- Dusk-singer
    ["6E379"] = "Pygargue de Brego", -- Brego's Erne
    ["6E37A"] = "Poule d'Holbyt", -- Holbyt-hen
    ["6E37B"] = "Fauvette des roseaux", -- Reed Warbler
    ["6E37C"] = "Plongeur à bec jaune", -- Yellow-billed Diver
    ["6E37D"] = "Longbec à ventre rouge", -- Red-breasted Longnib
    ["6E37E"] = "Avocette aux ailes noires", -- Black-winged Stilt
    ["6E37F"] = "Oie à pieds rouges", -- Red-footed Goose
    ["6E380"] = "Rôdeur de Tournesaule", -- Withy-mouse
    ["6E381"] = "Martinet de Firien", -- Firien-swift
    ["6E382"] = "Bécasseau des hauts-fonds", -- Undeep-stint
    ["6E383"] = "Fauvette blanche", -- Whither-warbler
    ["6E384"] = "Tarier pâtre de la Corne d'Argent", -- Silvertine Stonechat
    ["6E385"] = "Guêpier à tête bleue", -- Blue-cheeked Bee-eater
    ["6E386"] = "Pie-grièche de Fladrif", -- Fladrifs's Shrike
    ["6E387"] = "Fauvette des saules", -- Willow Warbler
    ["6E388"] = "Alouette de l'Onod", -- Onod-lark
    ["6E389"] = "Martinet des montagnes", -- Mountain Swift
    ["6FF96"] = "Aigle d’Aglazôr", -- Aglazor's Eagle
    ["6FF97"] = "Attrape-moucheron pâle", -- Pale Midge-catcher
    ["6FF98"] = "Brise-mât", -- Mastbreaker
    ["6FF99"] = "Fauvette olivâtre", -- Olive Warbler
    ["6FF9A"] = "Collerette crépusculaire", -- Dusky Ruff
    ["6FF9B"] = "Hirondelle striée", -- Streaked Swallow
    ["6FF9C"] = "Étourneau rosé", -- Rosy Starling
    ["6FF9D"] = "Bécasseau d’Ethir", -- Ethir-piper
    ["6FF9E"] = "Mouette du prince", -- Prince's Mew
    ["6FF9F"] = "Rouge-gorge à croupion blanc", -- White-rumped Ruddock
    ["6FFA0"] = "Colombe rieuse", -- Laughing Dove
    ["6FFA1"] = "Volaille d'Erech", -- Erech-Fowl
    ["6FFA2"] = "Marteleur pressé", -- Rush-hammer
    ["6FFA3"] = "Mésange cuivrée", -- Rust-tit
    ["6FFA4"] = "Corbeau du pendu", -- Hangman's Crow
    ["6FFA5"] = "Oiseau de Lhaereth", -- Lhaereth's Fowl
    ["6FFA6"] = "Martinet blême", -- Wan-swift
    ["6FFA7"] = "Pluvier-hirondelle", -- Swallow-plover
    ["6FFA8"] = "Cygne d’Amroth", -- Amroth-swan
    ["6FFA9"] = "Accenteur mouchet de Ciril", -- Ciril Dunnock
    ["6FFAA"] = "Vif-faucon", -- Keen-hawk
    ["6FFAB"] = "Bergeronnette couverte", -- Palled Wagtail
    ["6FFAC"] = "Vautour sinistre", -- Dire Vulture
    ["6FFAD"] = "Houlimande", -- Swelldrake
    ["6FFAE"] = "Cincle d’épouvante", -- Ghastly White-throat
    ["6FFAF"] = "Faucon du Morthond", -- Morthond Hawk
    ["6FFB0"] = "Geai de Tumladen", -- Tumladen Jay
    ["6FFB1"] = "Pouillot véloce de Lamedon", -- Lamedon Chiffchaff
    ["6FFB2"] = "Queue-blanche à gorge noire", -- Black-throated White-tail
    ["6FFB3"] = "Murinemarais", -- Bogmouse
    ["6FFB4"] = "Chouette mouchetée", -- Speckled Owl
    ["6FFB5"] = "Fauvette à queue rouge", -- Red-tailed Warbler
    ["6FFB6"] = "Fauvette gémissante", -- Wailing Warbler
    ["6FFB7"] = "Coliou", -- Bandymouse
    ["6FFB8"] = "Pinson de Ringlo", -- Ringlo Finch
    ["6FFB9"] = "Grattecaillou", -- Stonescraper
    ["6FFBA"] = "Puffin de Lantriel", -- Lantriel's Shearwater
    ["6FFBB"] = "Puffin à capuche", -- Cowled Shearwater
    ["6FFBC"] = "Murinefaucon", -- Hawmouse
    ["6FFBD"] = "Misère d’Ondoher", -- Ondoher's Woe
    ["6FFBE"] = "Poule d'Anor", -- Anor-hen
    ["6FFBF"] = "Rossignol voilé", -- Veiled Nightingale
    ["6FFC0"] = "Poule du cap", -- Cape-hen
    ["6FFC1"] = "Colvert huppé", -- Tufted Drake
    ["6FFC2"] = "Sterne de Falas", -- Falas Tern
    ["6FFC3"] = "Rouge-gorge des broussailles", -- Scrub Ruddock
    ["6FFC4"] = "Sterne gaie", -- Mirthful Tern
    ["6FFC5"] = "Troglodyte entortillé", -- Writhen-wren
    ["6FFC6"] = "Hibou de Durthang", -- Durthang Owl
    ["6FFC7"] = "Mésange aigrelette", -- Bitter Reedling
    ["6FFC8"] = "Courlis corlieu", -- Whimbrel
    ["6FFC9"] = "Corbeau de Calembel", -- Calembel Chough
    ["6FFCA"] = "Fauvette de Nimrodel", -- Nimrodel's Warbler
    ["6FFCB"] = "Batte-vent", -- Wind-beater
    ["6FFCC"] = "Bergeronnette chenue", -- Hoary Wagtail
    ["6FFCD"] = "Ombre-hibou", -- Shade-owl
    ["6FFCE"] = "Corbeau-deuil", -- Mourning-raven
    ["6FFCF"] = "Ténébreux marteleur", -- Darkling-hammer
    ["6FFD0"] = "Alouette de Giliath", -- Giliath Lark
    ["6FFD1"] = "Murinegrise", -- Greymouse
    ["6FFD2"] = "Étourneau béni", -- Hallow-starling
    ["6FFD3"] = "Cincle pâle", -- Pale Dipper
    ["6FFD4"] = "Geai vermeil", -- Ruddy Jay
    ["6FFD6"] = "Huppesang", -- Gorecrest
    ["6FFD7"] = "Pie-grièche écorcheuse", -- Corpse-shrike
    ["6FFD8"] = "Poule cendrée", -- Ash-hen
    ["6FFD9"] = "Fauvette-bourbier", -- Wallow-warbler
    ["6FFDA"] = "Pivert de Tarlang", -- Tarlang's Woodpecker
    ["6FFDB"] = "Petite ombre", -- Gloomling
    ["6FFDC"] = "Accenteur mouchet de Meneldil", -- Meneldil's Dunnock
    ["6FFDD"] = "Gravelot de Dagorlad", -- Dagorlad Plover
    ["6FFDE"] = "Collerette de Gilrain", -- Gilrain Ruff
    ["6FFDF"] = "Noirmarteau", -- Mirkhammer
    ["6FFE0"] = "Cormoran de Belfalas", -- Belfalas Cormorant
    ["6FFE1"] = "Pinsonscorie", -- Drossfinch
    ["6FFE2"] = "Fauvette grisette de Dun", -- Dun Whitethroat
    ["6FFE3"] = "Corbeau voilé", -- Shrouded Crow
    ["6FFE4"] = "Nuthatch lumineux", -- Bright Nuthatch
    ["6FFE5"] = "Melui-murine", -- Melui-mouse
    ["6FFE6"] = "Torcol rouge", -- Red Wryneck
    ["6FFE7"] = "Mornaigle", -- Drearhawk
    ["6FFE8"] = "Alouette-araignée", -- Spider-lark
    ["6FFE9"] = "Lustre-hibou", -- Sheen-owl
    ["6FFEA"] = "Pinsonsoleil", -- Sunfinch
    ["6FFEB"] = "Milan-carnage", -- Slaughter-kite
    ["6FFEC"] = "Huppegrise", -- Greycrest
    ["6FFED"] = "Geai gris", -- Grey Jay
    ["6FFEE"] = "Pivert de Cormallen", -- Cormallen Woodpecker
    ["6FFEF"] = "Cantateur de haies", -- Hedge-singer
    ["6FFF0"] = "Grue pleureuse", -- Weeping Crane
    ["6FFF1"] = "Sombre passereau", -- Sombre Tit
    ["6FFF2"] = "Sulidé du Lebennin", -- Lebennin Gannet
    ["6FFF3"] = "Queue d’argent", -- Silvertail
    ["6FFF4"] = "Moineau des neiges", -- Snow-sparrow
    ["6FFF5"] = "Queue d'épine", -- Spinetail
    ["6FFF6"] = "Toquesoir", -- Duskencap
    ["6FFF7"] = "Fauvette-Mindon", -- Mindon-warbler
    ["6FFF8"] = "Collerette tachée", -- Stained Ruff
    ["6FFF9"] = "Crave sinistre", -- Balefull Chough
    ["6FFFA"] = "Hibou-sentinelle", -- Warden-owl
    ["6FFFB"] = "Passereau noir", -- Blackchat
    ["6FFFC"] = "Mouette d'Argir", -- Argir-gull
    ["6FFFD"] = "Collimande sanglant", -- Bloody Dabdrake
    ["6FFFE"] = "Chardonnet", -- Thistling
    ["6FFFF"] = "Nuthatch pâle", -- Pale Nuthatch
    ["70000"] = "Bec-noueux de Lhingris", -- Lhingris Gnarebill
    ["70001"] = "Alouette gris-feuille", -- Greyleaf Skylark
    ["70002"] = "Pinson des friches", -- Fallowfinch
    ["70004"] = "Viftorrent", -- Riverswift
    ["70005"] = "Goéland de Brandur", -- Brandur's Gull
    ["70006"] = "Bécasseau-Sirith", -- Sirith-stint
    ["70007"] = "Gentillalouette", -- Sweetlark
    ["70008"] = "Bec-croisé d’Arnen", -- Arnen Crossbill
    ["70009"] = "Nuthatch d’Erui", -- Erui Nuthatch
    ["7000A"] = "Engoulevent crécelle", -- Rattling Nightiar
    ["7000B"] = "Appel-tempête d’Isildur", -- Isildur's Stormcaller
    ["7000C"] = "Bec-croisé d’Agarnaith", -- Agarnaith Gnarebill
    ["7000D"] = "Bergeronnette osseuse", -- Bony Wagtail
    ["7000E"] = "Hibou-flambeau", -- Beacon-owl
    ["7000F"] = "Pêcheur du havre", -- Haven-fisher
    ["70010"] = "Alouetteliche", -- Litchlark
    ["70011"] = "Grand plongeur de pont", -- Great Deck-diver
    ["70012"] = "Faucon-lune", -- Moon-hawk
    ["70013"] = "Geai d'Ithil", -- Ithil-jay
    ["70014"] = "Hibou-démon", -- Fiend-owl
    ["70015"] = "Bécasseau de Gladrist", -- Gladrist's Piper
    ["70016"] = "Grande fauvette", -- Great Warbler
    ["70017"] = "Pie bleue", -- Blue Magpie
    ["70018"] = "Faucon de Nimrais", -- Nimrais Hawk
    ["70019"] = "Moineau d’Andros", -- Andros Sparrow
    ["70881"] = "Poignée de graines pour oiseaux", -- Handful of Bird Feed
    ["709B8"] = "Esquisse représentant des corvidés curieux", -- Hand-sketched Painting of Curious Corvids
    ["709B9"] = "Esquisse représentant des colverts consciencieux", -- Hand-sketched Painting of Meticulous Mallards
    ["709BA"] = "Esquisse représentant un perchoir particulier", -- Hand-sketched Painting of a Peticular Perching
}
for id,name in pairs(NamesFR) do
    if BL_ID[id] then
        BL_ID[id].ln = name
    elseif BL_GID[id] then
        BL_GID[id].ln = name
    end
end

-- Return the best display name without changing internal English identifiers.
function BL_Name(id)
    local t = BL_ID[id]
    if not t then return "?" end
    return t.ln or t.n
end

function BL_ZoneName(zc)
    local t = BL_Zone[zc]
    if not t then return tostring(zc) end
    return t.ln or t.z
end

function BL_RebuildNameIndex()
    BL_Bname = BL_Bname or {}
    for id,t in pairs(BL_ID) do
        BL_Bname[t.n] = id
        if t.ln then BL_Bname[t.ln] = id end
    end
end

BL_RebuildNameIndex()

-- Titres de progression propres à l'addon (ils n'ont pas été retrouvés dans le DAT FR).
-- Titres de récompense officiels affichés aux paliers d'ornithologie.
BL_TitleFR = {
    [10]="Amateur d'oiseaux",
    [30]="Oiseleur",
    [50]="Fauvette acharnée",
    [70]="Connaisseur d’ailes",
    [100]="Dompteur d’oiseaux",
}
