-- Birding Log Data
-- coding: utf-8 'ä

BL_BirdingKit = 104 -- item category
BL_Found = "Erhalten: "
BL_Loc = ";pos"
BL_Region = { Eriador=1, Rhovanion=2, Gondor=3, Mordor=4, Haradwaith=5 }
BL_RegN = {}
for name,ix in pairs(BL_Region) do BL_RegN[ix] = name end

BL_Zone = {
		['Ag']={z="Agarnaith", r=4, n=-46, s=-57, e=37, w=25 },
		['An']={z="Angmar", r=1, n=13, s=-4, e=-15, w=-41 },
		['Ar']={z="Anórien", r=3, n=-36, s=-72, e=-10, w=-47 },
		['Bf']={z="Belfalas", r=3, n=-72, s=-82, e=-60, w=-74 },
		['Br']={z="Breeland", r=1, n=-18.5, s=-37, e=-42, w=-63 },
		['Ca']={z="Cardolan", r=1, n=-37, s=-55, e=-28, w=-56 },
		['Cl']={z="Das Ackerland", r=2, n=-43, s=-65, e=-52, w=-65 },
		['Du']={z="Dunland", r=1, n=-75, s=-90, e=1, w=-26 },
		['Ef']={z="Ostfold", r=2, n=-53, s=-74, e=-53, w=-75 },
		['En']={z="Enedwaith", r=1, n=-57, s=-75, e=-9, w=-24 },
		['EL']={z="Ered Luin", r=1, n=-13, s=-29, e=-89, w=-108 },
		['Er']={z="Eregion", r=1, n=-40, s=-57, e=-6, w=-19 },
		['Ev']={z="Evendim", r=1, n=-3, s=-20, e=-60, w=-76 },
		['Ew']={z="Entwasser", r=2, n=-40, s=-53, e=-59, w=-76 },
		['Fg']={z="Fangorn", r=2, n=-37.5, s=-44, e=-78, w=-85 },
		['Fo']={z="Forochel", r=1, n=21, s=-3, e=-57, w=-89 },
		['GR']={z="Großer Fluss", r=2, n=-19.5, s=-33, e=-48, w=-72 },
		['It']={z="Ithilien", r=3, n=-62, s=-77, e=-3, w=-19 },
		['Ld']={z="Lamedon", r=3, n=-60, s=-72, e=-54, w=-62 },
		['Le']={z="Lebennin", r=3, n=-71, s=-86, e=-31, w=-53 },
		['Lh']={z="Lhingris", r=4, n=-48, s=-64, e=12.1, w=2 },
		['La']={z="Lossarnach", r=3, n=-71.5, s=-80, e=-19, w=-26 },
		['Ll']={z="Lothlórien", r=2, n=-9.5, s=-19.5, e=-62, w=-74 },
		['Lo']={z="Die Einsamen Lande", r=1, n=-28, s=-38, e=-23, w=-42 },
		['Mw']={z="Düsterwald", r=2, n=-8, s=-20, e=-41, w=-62 },
		['MM']={z="Das Nebelgebirge", r=1, n=-17, s=-32, e=9, w=-4 },
		['ND']={z="Die Nordhöhen", r=1, n=-4, s=-18.5, e=-33, w=-60 },
		['Sh']={z="Das Auenland", r=1, n=-20, s=-38, e=-63, w=-88 },
		['Sw']={z="Schwanenfleet", r=1, n=-50, s=-66, e=-18, w=-36 },
		['Tr']={z="Die Trollhöhen", r=1, n=-26, s=-44, e=-4, w=-24 },
		['TW']={z="Das Ödland", r=4, n=-27, s=-41, e=2, w=-15.5 },
		['tW']={z="Die Steppe", r=2, n=-30, s=-47, e=-45, w=-73 },
		['Wf']={z="Westfold", r=2, n=-53.5, s=-66, e=-76, w=-91 },
	}
BL_Zname,BL_Zlist = {}, {}
for zc,zt in Sort(BL_Zone) do 
	BL_Zname[zt.z] = zc
	table.insert(BL_Zlist,zt.z)
end

BL_Title = { [10]="Spatzenhirn", [30]="Vogelfrei", [50]="Adlerauge", 
			[70]="Federfinder", [100]="Vogelzähmer" }

BL_GID = {	
	["6B916"] = {n="Orange-blaue Mithrilkleidung der Vogelbeobachtung",z="Schwanenfleet"},
	["6B920"] = {n="Orange Mithrilkleidung der Vogelbeobachtung",z="Dunland"},
	["6B927"] = {n="Blaue Mithrilkleidung der Vogelbeobachtung",z="das Nebelgebirge"},
	["6B928"] = {n="Orange-schwarze Kleidung der Vogelbeobachtung",z="Forochel"},
	["6B92A"] = {n="Blau-goldene Kleidung der Vogelbeobachtung",z="Ered Luin"},
	["6B92B"] = {n="Blaue Kleidung der Vogelbeobachtung",z="Breeland"},
	["6B92C"] = {n="Orange-goldene Kleidung der Vogelbeobachtung",z="Angmar"},
	["6B92E"] = {n="Blau-schwarze Kleidung der Vogelbeobachtung",z="die Trollhöhen"},
	["70881"] = {n="Handful of Bird Feed",z=""},
	["709B9"] = {n="Hand-sketched Painting of Meticulous Mallards",z=""},
	["709B8"] = {n="Hand-sketched Painting of Curious Corvids",z=""},
	["709BA"] = {n="Handgemaltes Gemälde einer besonderen Sitzstange",z=""},
--	["6B900"] = {n="Hut des Vogelbeobachters",z="Die seltensten Vögel von Eriador"},
	}

BL_ID = {	
		["6E351"] = {n="Ackergans",f={'Cl','Ew'}},
       		["7000C"] = {n="Agarnaith-Krummschnabel",f={'Ag'}},
		["6FF96"] = {n="Aglazôrs Adler",f={'Bf'}},
		["6FFA8"] = {n="Amroth-Sperling",f={'Bf'}},
		["70019"] = {n="Andros-Sperling",f={'It','La'}},
		["6E353"] = {n="Anduin-Adler",f={'Ef','Ar'}},
		["6FFBE"] = {n="Anor-Huhn",f={'Ar'}},
		["6BC7D"] = {n="Arantars Seeschwalbe",f={'Lo'}},
     		["6FFFC"] = {n="Argir-Möwe",f={'Le'}},
       		["70008"] = {n="Arnen-Kreuzschnabel",f={'It'}},
		["6BB86"] = {n="Arnorischer Falke",f={'Ev'}},
		["6FFD8"] = {n="Aschhahn",f={'TW'}},
		["6BBDA"] = {n="Aschengeier",f={'An'}},
		["6FFF9"] = {n="Rachsüchtige Krähe",f={'Ag'}},
		["6FFB7"] = {n="Streifenmeise",f={'Ld'}},
		["6BB78"] = {n="Balkenschwanz-Uferschnepfe",f={'Fo'}},
		["6BBB7"] = {n="Gerstenvogel",f={'EL'}},
		["6E35A"] = {n="Sperbergrasmücke",f={'Cl'}},
		["6BC82"] = {n="Einöden-Brandente",f={'An'}},
		["6BC02"] = {n="Einöden-Watvogel",f={'Ca'}},
      		["7000E"] = {n="Leuchtfeuer-Eule",f={'Ar'}},
		["6BC6C"] = {n="Belegs Würger",f={'ND'}},
		["6E376"] = {n="Beleriand-Schwan",f={'Ll'}},
		["6FFE0"] = {n="Belfalas-Kormoran",f={'Bf','Le'}},
		["6E343"] = {n="Bartmoorhahn",f={'Cl'}},
		["6FFC7"] = {n="Bittermeise",f={'Ag'}},
		["6BB63"] = {n="Schwarzrückenmöwe",f={'Fo'}},
		["6E32C"] = {n="Kappenammer",f={'Fg'}},
		["6BB9E"] = {n="Schwarzkopfmöwe",f={'EL','Ev'}},
		["6E314"] = {n="Uferschnepfe",f={'Ew'}},
		["6E360"] = {n="Prachttaucher",f={'Ew'}},
		["6E369"] = {n="Schwarzhalsbraunelle",f={'Fg'}},
		["6FFB2"] = {n="Schwarzkehliger Weißschwanz",f={'La'}},
		["6E37E"] = {n="Stelzenläufer",f={'Ef'}},
		["6BBF0"] = {n="Schwarzer Milan",f={'Tr','Er'}},
		["6E34B"] = {n="Schwarzstorch",f={'Mw'}},
		["6E327"] = {n="Schwarzer Schwan",f={'GR'}},
		["6BBD1"] = {n="Schwarzhaube",f={'MM'}},
		["6FFFB"] = {n="Schwarzer Schmätzer",f={'Lh'}},
		["6BBD3"] = {n="Froher Kiebitz",f={'En'}},
		["6FFFD"] = {n="Blutiger Kleckserpel",f={'Ag'}},
		["6E361"] = {n="Blaue Weihe",f={'tW'}},
      		["70017"] = {n="Dickschnabelkitta",f={'Bf'}},
		["6E312"] = {n="Blaudrossel",f={'Cl'}},
		["6BBE1"] = {n="Blaumeise",f={'MM'}},
		["6E385"] = {n="Blauwangenspint",f={'Wf'}},
		["6BBF7"] = {n="Blauschwanzrotkehlchen",f={'En'}},
		["6BC1F"] = {n="Blauschnabel",f={'An'}},
		["6FFB3"] = {n="Sumpfmeise",f={'TW'}},
		["6BBF9"] = {n="Moorschnepfe",f={'Du'}},
        	["7000D"] = {n="Knochige Stelze",f={'TW'}},
		["6B44B"] = {n="Bergfink",f={'Sh'}},
    		["70005"] = {n="Brandurs Möwe",f={'La'}},
		["6BBCC"] = {n="Brandy-Sänger",f={'Br'}},
		["6BBF8"] = {n="Ringelgans",f={'An','Fo'}},
		["6BBB4"] = {n="Bree-Drossel",f={'Br'}},
		["6E379"] = {n="Bregos Seeadler",f={'Cl'}},
		["6FFE4"] = {n="Heller Kleiber",f={'It'}},
		["6E368"] = {n="Weißschwanz der Weiten Mark",f={'Ew'}},
		["6BBDE"] = {n="Bruinen-Fink",f={'Tr'}},
		["6BC1B"] = {n="Gimpel",f={'MM'}},
		["6BB69"] = {n="Metzgervogel",f={'En'}},
		["6BBCD"] = {n="Calanor-Lerche",f={'Er'}},
		["6FFC9"] = {n="Calembel-Krähe",f={'Ld'}},
		["6FFC0"] = {n="Kaphuhn",f={'Bf'}},
		["6BBA0"] = {n="Celebríans Ammer",f={'Tr'}},
		["6E352"] = {n="Celebrant-Kreuzschnabel",f={'GR'}},
		["6B451"] = {n="Buchfink",f={'EL','Sh'}},
		["6B43C"] = {n="Chetwaldspecht",f={'Br'}},
		["6BB7F"] = {n="Zilpzalp",f={'ND'}},
		["6FFA9"] = {n="Ciril-Braunelle",f={'Bf','Ld'}},
		["6E329"] = {n="Cirios Seeschwalbe",f={'GR'}},
		["6E34E"] = {n="Spaltenregenpfeifer",f={'GR','tW'}},
		["6BB6E"] = {n="Klippenschwalbe",f={'EL'}},
		["6BBFC"] = {n="Klippenläufer",f={'MM'}},
		["6E32F"] = {n="Halsband-Mückenfänger",f={'Fg'}},
		["6E321"] = {n="Halsband-Moorling",f={'tW'}},
		["6FFEE"] = {n="Cormallen-Specht",f={'It'}},
		["6FFD7"] = {n="Leichenwürger",f={'TW'}},
		["6E358"] = {n="Hausschwalbe",f={'Wf'}},
		["6FFBB"] = {n="Hauben-Sturmtaucher",f={'Le'}},
		["6BB88"] = {n="Felsenschwalbe",f={'Du'}},
		["6BB9B"] = {n="Kranich",f={'Sw'}},
		["6E30C"] = {n="Haubenmeise",f={'Ll','Mw'}},
		["6E344"] = {n="Ackerkauz",f={'Cl'}},
		["6BC7A"] = {n="Klagereiher",f={'Ev'}},
		["6BBC3"] = {n="Kuckuck",f={'Ca'}},
		["6FFDD"] = {n="Dagorlad-Regenpfeifer",f={'TW'}},
		["6FFCF"] = {n="Finsterlingsammer",f={'Ag'}},
		["6E365"] = {n="Klamm-Braunelle",f={'Wf'}},
		["6E35F"] = {n="Schattenbach-Sommergoldhähnchen",f={'Ll'}},
		["6FFAC"] = {n="Unheilsgeier",f={'Lh'}},
		["6BC16"] = {n="Mornell",f={'ND'}},
		["6BBE0"] = {n="Höhenammer",f={'ND'}},
		["6BB70"] = {n="Drachenjagender Adler",f={'Du'}},
		["6FFE7"] = {n="Düsterfalke",f={'TW'}},
		["6FFE1"] = {n="Todesfink",f={'Ag'}},
		["6BBF2"] = {n="Drúens Ammer",f={'Du'}},
		["6E317"] = {n="Falb-Wiesenpieper",f={'Cl','Ef'}},
		["6FFE2"] = {n="Hellbraune Weißkehle",f={'TW'}},
		["6BBD0"] = {n="Dunkrähe",f={'En','Du'}},
		["6BB84"] = {n="Dunhuhn",f={'Du'}},
		["6BB9A"] = {n="Heckenbraunelle",f={'ND'}},
		["6FFC6"] = {n="Durthang-Eule",f={'Lh'}},
		["6BBE9"] = {n="Düsterjäger",f={'An'}},
		["6E378"] = {n="Dämmerungssänger",f={'Mw'}},
		["6FFF6"] = {n="Dämmerkappe",f={'Ar','It'}},
		["6FF9A"] = {n="Brauner Kampfläufer",f={'It'}},
		["6BB9F"] = {n="Zwergenganter",f={'MM'}},
		["6E34C"] = {n="Uhu",f={'Fg'}},
		["6BB65"] = {n="Edhel-Schwan",f={'Sw'}},
		["6E31A"] = {n="Egladil-Specht",f={'Ll'}},
		["6BB74"] = {n="Eider",f={'EL'}},
		["6E32E"] = {n="Ent-Specht",f={'Fg'}},
		["6E319"] = {n="Entwasser-Wiesenpieper",f={'Ew'}},
		["6E333"] = {n="Éohilds Sänger",f={'Ef'}},
		["6E36C"] = {n="Eorls Sänger",f={'tW'}},
		["6FFA1"] = {n="Erech-Huhn",f={'Ld'}},
		["6BBC1"] = {n="Ereglad-Specht",f={'Er'}},
		["6BB79"] = {n="Eriador-Häher",f={'Lo'}},
		["6E342"] = {n="Ersc-Huhn",f={'tW'}},
		["70009"] = {n="Erui-Kleiber",f={'La'}},
		["6BBA1"] = {n="Etelans Sturmrufer",f={'Fo'}},
		["6FF9D"] = {n="Ethir-Pieper",f={'La','Le'}},
		["6BC09"] = {n="Ettenmeise",f={'Tr'}},
		["6BBE2"] = {n="Even-Taube",f={'Ev'}},
		["6E320"] = {n="Abendfalke",f={'Mw'}},
		["6E341"] = {n="Everholt-Drossel",f={'Ef'}},
		["6BC75"] = {n="Fadráchs Fehnling",f={'An'}},
		["6FFC2"] = {n="Falas-Seeschwalbe",f={'Bf'}},
		["6BBD8"] = {n="Falathlorn-Specht",f={'EL'}},
		["6E32D"] = {n="Falbjunges",f={'Cl'}},
        	["70002"] = {n="Falbfink",f={'Ld'}},
		["6E334"] = {n="Fangorn-Sänger",f={'Fg'}},
		["6E33D"] = {n="Unheilskrähe",f={'Mw','GR'}},
		["6E35B"] = {n="Marschläufer",f={'GR'}},
		["6BBFE"] = {n="Sumpfmeise",f={'Sw'}},
		["6E374"] = {n="Fenmark-Pieper",f={'Ef'}},
		["6BBC7"] = {n="Tannengans",f={'Fo'}},
		["6E32B"] = {n="Fimbrethils Sommergoldhähnchen",f={'Fg'}},
		["70014"] = {n="Unheilseule",f={'Ag'}},
		["6BBEA"] = {n="Sommergoldhähnchen",f={'Er'}},
		["6E381"] = {n="Firienschwalbe",f={'Ef'}},
		["6E386"] = {n="Fladrifs Würger",f={'Fg'}},
		["6BB6D"] = {n="Fleetläufer",f={'Sw'}},
		["6BBC9"] = {n="Feldsänger",f={'Du','Wf'}},
		["6BC73"] = {n="Fornost-Falke",f={'ND'}},
		["6E34D"] = {n="Fuchsfalke",f={'Ew'}},
		["6FFAE"] = {n="Grauenhafte Weißkehle",f={'Ag'}},
		["6FFD0"] = {n="Giliath-Lerche",f={'It'}},
		["6FFDE"] = {n="Gilrain-Kampfläufer",f={'Le'}},
        	["70015"] = {n="Gladrists Pfeifer",f={'Bf'}},
		["6BB7D"] = {n="Zwielichtsänger",f={'Er'}},
		["6FFDB"] = {n="Düsterling",f={'Lh'}},
		["6BB8B"] = {n="Goldhähnchen",f={'ND'}},
		["6BC1C"] = {n="Goldadler",f={'MM'}},
		["6BBAD"] = {n="Goldregenpfeifer",f={'Ca','Lo'}},
		["6E371"] = {n="Goldsänger",f={'Ll'}},
		["6BC6E"] = {n="Golddrossel",f={'Tr'}},
		["6B445"] = {n="Distelfink",f={'Br'}},
		["6BBED"] = {n="Gänsesäger",f={'Ca','Sw'}},
		["6FFD6"] = {n="Blutkamm",f={'Ag'}},
		["6BB72"] = {n="Deutwald-Kreuzschnabel",f={'Du'}},
        	["70011"] = {n="Großer Taucher",f={'Le'}},
		["70016"] = {n="Großer Sänger",f={'Ld'}},
		["6B448"] = {n="Grünfink",f={'Sh'}},
		["6BB94"] = {n="Grünschenkel",f={'Fo'}},
		["6BBB3"] = {n="Graureiher",f={'Tr','Sw'}},
		["6FFED"] = {n="Grauhäher",f={'Lh','TW'}},
		["6BC26"] = {n="Grauer Mückenfänger",f={'En'}},
		["6E355"] = {n="Grauer Würger",f={'Ew'}},
		["6BB8E"] = {n="Graustelze",f={'Ev'}},
		["6FFEC"] = {n="Graukamm",f={'TW'}},
		["6E356"] = {n="Graudohle",f={'Wf'}},
		["6BBA4"] = {n="Grauflut-Seeschwalbe",f={'Ca'}},
		["6BBA9"] = {n="Graugans",f={'Br'}},
        	["70001"] = {n="Graublatt-Feldlerche",f={'Bf'}},
		["6FFD1"] = {n="Graumeise",f={'It'}},
		["6BBE4"] = {n="Klageeule",f={'Er'}},
		["6E318"] = {n="Guldur-Würger",f={'Mw'}},
		["6FFD2"] = {n="Heiliger Star",f={'Ar'}},
		["6E377"] = {n="Hammerkläger",f={'tW'}},
		["6BB7C"] = {n="Hängenestmeise",f={'Er'}},
		["6FFA4"] = {n="Henkerskrähe",f={'Lh'}},
		["6E346"] = {n="Eggeneule",f={'Ef'}},
		["6BBD4"] = {n="Ernteammer",f={'Lo'}},
		["6E35E"] = {n="Geistersänger",f={'Mw'}},
        	["7000F"] = {n="Hafenfischer",f={'Bf'}},
		["6BBA3"] = {n="Kernbeißer",f={'Lo'}},
		["6FFBC"] = {n="Heckenmeise",f={'Ar'}},
		["6BC7E"] = {n="Haselhuhn",f={'Tr'}},
		["6BB75"] = {n="Heideroller",f={'Du'}},
		["6BB71"] = {n="Heidehuhn",f={'An'}},
		["6FFEF"] = {n="Heckensänger",f={'Le'}},
		["6E33A"] = {n="Helms Seeadler",f={'Wf'}},
		["6E34F"] = {n="Behelmte Sturmmöwe",f={'Ef','Ar'}},
		["6BB95"] = {n="Silbermöwe",f={'Fo'}},
		["6E31F"] = {n="Blaumeise",f={'Ef'}},
		["6BB85"] = {n="Hithaeglir-Dohle",f={'MM'}},
		["6FFCC"] = {n="Raureifstelze",f={'Ld'}},
		["6E37A"] = {n="Holbyt-Huhn",f={'Cl','Ew'}},
		["6BBAC"] = {n="Stechpalmenspatz",f={'Er'}},
		["6E354"] = {n="Wiedehopf",f={'Cl'}},
		["6E326"] = {n="Gehörntes Tauchentchen",f={'Mw','GR'}},
		["6BC1A"] = {n="Gehörnter Springer",f={'An'}},
		["6E36F"] = {n="Hulvester",f={'Ef'}},
		["6E34A"] = {n="Jagdfalke",f={'Wf'}},
		["6BC25"] = {n="Eisbucht-Regenpfeifer",f={'Fo'}},
		["6E347"] = {n="Irensaga-Seeschwalbe",f={'Ef'}},
		["6BBF3"] = {n="Eisenseidenschwanz",f={'An'}},
		["6BBAE"] = {n="Isen-Gans",f={'Du'}},
		["6BBDB"] = {n="Isilcars Lerche",f={'Ca'}},
        	["7000B"] = {n="Isildurs Sturmrufer",f={'Le'}},
        	["70013"] = {n="Ithil-Häher",f={'It'}},
		["6B434"] = {n="Dohle",f={'Br','Lo'}},
		["6FFAA"] = {n="Scharfblickfalke",f={'Ar'}},
		["6E322"] = {n="Eisvogel",f={'Fg','Ll'}},
		["6BC71"] = {n="Königsfall-Amsel",f={'ND','MM'}},
		["6BBB6"] = {n="Laeglin Sänger",f={'En'}},
		["6FFB1"] = {n="Lamedon-Zilpzalp",f={'Ld'}},
		["6FFBA"] = {n="Lantriels Sturmtaucher",f={'Bf'}},
		["6FFA0"] = {n="Lachtaube",f={'Ld'}},
		["6E370"] = {n="Lorbeer-Ringeltaube",f={'Ll'}},
        	["6FFF2"] = {n="Lebennin-Tölpel",f={'Le','Bf'}},
		["6FFA5"] = {n="Lhaereths Rebhuhn",f={'Ag'}},
        	["70000"] = {n="Lhingris-Krummschnabel",f={'Lh'}},
		["6B449"] = {n="Bluthänfling",f={'Sh'}},
		["6BBBA"] = {n="Lindions Sänger",f={'Tr'}},
		["6E336"] = {n="Limklar-Bachstelze",f={'Fg','tW'}},
        	["70010"] = {n="Lich-Lerche",f={'Ag'}},
		["6BC72"] = {n="Einsamer Habicht",f={'Lo'}},
		["6BBD9"] = {n="Eisente",f={'Ev','ND'}},
		["6BBDF"] = {n="Schwanzmeise",f={'Fo'}},
		["6BC78"] = {n="Langbeinreiher",f={'Lo'}},
		["6BB6B"] = {n="Fürstenreiher",f={'Sw'}},
		["6BB97"] = {n="Luin-Star",f={'EL','Ev'}},
		["6E32A"] = {n="Lauerbaumläufer",f={'Mw'}},
		["6BC0F"] = {n="Madelgards Stelze",f={'Sh'}},
		["6BBC0"] = {n="Elster",f={'ND'}},
		["6E33B"] = {n="Jungfernkranich",f={'Cl'}},
		["6B441"] = {n="Stockente",f={'Br'}},
		["6E348"] = {n="Mallornfink",f={'Ll'}},
		["6BC7C"] = {n="Bruch-Tauchentchen",f={'Sh'}},
		["6BBA8"] = {n="Sumpfrohrsänger",f={'Sw'}},
		["6E350"] = {n="Maskierter Metzgervogel",f={'Wf'}},
		["6E363"] = {n="Maskierte Grasmücke",f={'GR'}},
		["6FF98"] = {n="Mastbrecher",f={'La'}},
		["6BB6C"] = {n="Wiesenpieper",f={'Sh'}},
		["6FFE5"] = {n="Melui-Meise",f={'La'}},
		["6BC28"] = {n="Meluinen-Wasserhuhn",f={'ND'}},
		["6FFDC"] = {n="Meneldils Braunelle",f={'Ar'}},
		["6BC29"] = {n="Methedras-Nachtigall",f={'Du','Wf'}},
		["6BBC6"] = {n="Mückenfänger",f={'An'}},
		["6BBB2"] = {n="Mückenwasser-Kiebitz",f={'Br'}},
        	["6FFF7"] = {n="Mindon-Sänger",f={'Ar'}},
		["6E313"] = {n="Sumpfhuhn",f={'tW'}},
		["6E332"] = {n="Düsterspecht",f={'Mw'}},
		["6FFDF"] = {n="Düsterammer",f={'Lh'}},
		["6FFC4"] = {n="Fröhliche Seeschwalbe",f={'Le'}},
		["6BC74"] = {n="Nebelkampfläufer",f={'Er'}},
		["6E323"] = {n="Nebelsänger",f={'Fg','Ll'}},
		["6BC27"] = {n="Misteldrossel",f={'An'}},
		["6BBC2"] = {n="Nebelgebirge-Hüpfer",f={'MM'}},
		["6BB91"] = {n="Nebeleule",f={'MM'}},
		["6BC79"] = {n="Mitheithel-Tauchentchen",f={'Sw'}},
        	["70012"] = {n="Mondhabicht",f={'It'}},
		["6BC6D"] = {n="Moorschneehuhn",f={'Lo'}},
		["6B450"] = {n="Teichralle",f={'Br'}},
      		["6FFAF"] = {n="Morthond-Habicht",f={'Ld'}},
		["6BB80"] = {n="Moospieper",f={'Er'}},
		["6E389"] = {n="Bergschwalbe",f={'Fg'}},
		["6BB90"] = {n="Trauerbaumläufer",f={'Tr'}},
		["6FFCE"] = {n="Trauerrabe",f={'It'}},
		["6BBFD"] = {n="Trauerhöhe-Bienenfresser",f={'En'}},
		["6BBE3"] = {n="Narfang-Uferläufer",f={'EL'}},
		["6BC11"] = {n="Naug-Rohrdommel",f={'Sw'}},
		["6BC04"] = {n="Nenuial-Seeschwalbe",f={'Ev'}},
		["6BB73"] = {n="Nethorns Ammer",f={'Sw'}},
		["6E337"] = {n="Nachtkrönchen",f={'Ll','Mw'}},
		["6E372"] = {n="Nightreiher",f={'Mw'}},
		["6E310"] = {n="Nachtschattenammer",f={'Mw'}},
    		["70018"] = {n="Nimrais-Bussard",f={'La'}},
		["6E362"] = {n="Nimrodel-Pieper",f={'Ll'}},
		["6FFCA"] = {n="Nimrodels Sänger",f={'Bf'}},
		["6BBBC"] = {n="Nordschwalbe",f={'Fo'}},
		["6BBCF"] = {n="Nordviertelgimpel",f={'Sh'}},
		["6BC18"] = {n="Nussknacker",f={'Tr'}},
		["6BB98"] = {n="Spechtmeise",f={'MM'}},
		["6FF99"] = {n="Olivgrüner Sänger",f={'It'}},
		["6FFBD"] = {n="Ondohers Weh",f={'TW'}},
		["6E388"] = {n="Onod-Lerche",f={'Fg'}},
		["6BB66"] = {n="Oranorils Sänger",f={'Er'}},
		["6BBEB"] = {n="Orthon-Erpel",f={'An','Fo'}},
		["6FFD3"] = {n="Fahle Wasseramsel",f={'La'}},
		["6FF97"] = {n="Fahler Mückenfänger",f={'It'}},
       	 	["6FFFF"] = {n="Fahler Kleiber",f={'Ld'}},
		["6BBA5"] = {n="Bleichmantelweihe",f={'En'}},
		["6FFAB"] = {n="Blasse Stelze",f={'Ag'}},
		["6BB67"] = {n="Wanderfalke",f={'MM'}},
		["6BBE5"] = {n="Perian-Eule",f={'Tr'}},
		["6BBDD"] = {n="Zwergfalke",f={'Ca'}},
		["6E311"] = {n="Kleiner Kormoran",f={'GR'}},
		["6BB96"] = {n="Fichtenammer",f={'MM'}},
		["6BBB9"] = {n="Kurzschnabelgans",f={'EL'}},
		["6BB92"] = {n="Regenbogenspint",f={'An'}},
		["6BC19"] = {n="Tafelente",f={'Ev','ND'}},
		["6FF9E"] = {n="Prinzenmöwe",f={'Bf'}},
		["6E338"] = {n="Purpurreiher",f={'Ew'}},
        	["7000A"] = {n="Rasselnde Nachtschwalbe",f={'Lh'}},
		["6BBBD"] = {n="Rotmilan",f={'Sh'}},
		["6FFE6"] = {n="Roter Wendehals",f={'Ar'}},
		["6BB77"] = {n="Rotschnabelkrähe",f={'Ev'}},
		["6BBF1"] = {n="Scharlachkehlchen",f={'Br','Sh'}},
		["6E37D"] = {n="Rotbrustlangfeder",f={'GR'}},
		["6E33C"] = {n="Rotbrustmückenfresser",f={'Ew'}},
		["6E37F"] = {n="Rotfußgans",f={'GR'}},
		["6E35C"] = {n="Rotköpfchen",f={'Fg'}},
		["6FFB5"] = {n="Rotschwänziger Sänger",f={'La'}},
		["6BC6B"] = {n="Sterntaucher",f={'Fo'}},
		["6E36A"] = {n="Rotkehlpieper",f={'GR'}},
		["6BBAF"] = {n="Rotschopferpel",f={'Du'}},
		["6BBCB"] = {n="Rothornfalke",f={'Er'}},
		["6BBD7"] = {n="Knutt",f={'Fo'}},
		["6BB68"] = {n="Birkenzeisig",f={'Ev'}},
		["6BBC4"] = {n="Purpurstielzchen",f={'EL'}},
		["6B44D"] = {n="Rotdrossel",f={'Br'}},
		["6BB93"] = {n="Rohammer",f={'Sh'}},
		["6E37B"] = {n="Rohrsänger",f={'Ew','Wf'}},
		["6BC0E"] = {n="Bartmeise",f={'En'}},
		["6BB8A"] = {n="Rhudaur-Gans",f={'Tr'}},
		["6E373"] = {n="Rillensänger",f={'GR','tW'}},
		["6BBBE"] = {n="Ringelamsel",f={'Ca'}},
		["6FFB8"] = {n="Ringló-Fink",f={'La'}},
		["6BC07"] = {n="Bruchtal-Specht",f={'Tr'}},
		["6BC22"] = {n="Schlagschwirl",f={'En'}},
    		["70004"] = {n="Flussschwalbe",f={'La','Le'}},
		["6BC12"] = {n="Felsenammer",f={'Ca'}},
		["6BC80"] = {n="Felsentaube",f={'EL'}},
		["6E375"] = {n="Felsendrossel",f={'tW'}},
		["6BC10"] = {n="Saatkrähe",f={'EL'}},
		["6BBE8"] = {n="Rosensänger",f={'Ca'}},
		["6FF9C"] = {n="Rosenstar",f={'La'}},
		["6FFD4"] = {n="Rothäher",f={'Ld'}},
		["6E339"] = {n="Rotpieper",f={'tW'}},
		["6BC6F"] = {n="Rotes Stoppelhuhn",f={'Ca'}},
		["6E30D"] = {n="Rostgans",f={'Ef'}},
		["6BC03"] = {n="Rotschwalbe",f={'En'}},
		["6E328"] = {n="Trauertaube",f={'Ll'}},
		["6FFA2"] = {n="Flinkammer",f={'TW'}},
		["6E335"] = {n="Binsenlachenrohrdommel",f={'GR'}},
		["6BBBB"] = {n="Binsenschnepfe",f={'Sh'}},
		["6E330"] = {n="Rostschwalbe",f={'Fg','tW'}},
		["6FFA3"] = {n="Rostmeise",f={'Le'}},
		["6BB81"] = {n="Meerente",f={'Fo'}},
		["6FFC3"] = {n="Buschkehlchen",f={'Ag'}},
		["6BB7E"] = {n="Schilfrohrsänger",f={'Ca'}},
		["6E366"] = {n="Binsenscherer",f={'Cl'}},
		["6E316"] = {n="Schattenwasserrötel",f={'Mw'}},
		["6FFCD"] = {n="Schatteneule",f={'TW'}},
		["6BBA2"] = {n="Watwasserhuhn",f={'Tr','Sw'}},
		["6FFE9"] = {n="Glanzeule",f={'La'}},
		["6E36D"] = {n="Schaufelreiher",f={'GR'}},
		["6BB6F"] = {n="Löffelente",f={'Lo'}},
		["6FFE3"] = {n="Mantelkrähe",f={'TW'}},
		["6BBEF"] = {n="Schleiererpel",f={'An'}},
		["6BBAB"] = {n="Sichelbrachläufer",f={'Ev'}},
		["6E35D"] = {n="Sichelschnabel",f={'Ew'}},
		["6E30F"] = {n="Silberosthuhn",f={'Cl','Ef'}},
		["6BBBF"] = {n="Silberstorch",f={'Sw'}},
		["6E345"] = {n="Silbergans",f={'Wf'}},
        	["6FFF3"] = {n="Silberschwanz",f={'Ar'}},
		["6BC13"] = {n="Silberzinnenweihe",f={'Er'}},
		["6E384"] = {n="Silberzinnen-Schwarzkehlchen",f={'Ll'}},
        	["70006"] = {n="Sirith-Wasserläufer",f={'Le'}},
		["6B436"] = {n="Feldlerche",f={'Br'}},
		["6FFEB"] = {n="Blutmilan",f={'Ag'}},
		["6B43D"] = {n="Uferschwalbe",f={'Sh'}},
		["6BBEC"] = {n="Schneemilan",f={'Fo'}},
        	["6FFF4"] = {n="Schneespatz",f={'Ld'}},
		["6E364"] = {n="Schneegrenzenpieper",f={'Cl'}},
		["6BB6A"] = {n="Würdenmeise",f={'Lo'}},
		["6E357"] = {n="Düsterlerche",f={'Mw'}},
		["6FFF1"] = {n="Düstermeise",f={'Lh'}},
		["6BB62"] = {n="Singdrossel",f={'MM','ND'}},
		["6B44F"] = {n="Sperber",f={'Br'}},
		["6E367"] = {n="Speerhuhn",f={'Cl'}},
		["6E359"] = {n="Geflecktes Blaukehlchen",f={'Ef'}},
		["6FFB4"] = {n="Sprenkeleule",f={'Ld'}},
		["6FFE8"] = {n="Spinnenlerche",f={'Lh'}},
		["6FFF5"] = {n="Segler",f={'Lh'}},
		["6E340"] = {n="Häherkuckuck",f={'Fg'}},
		["6BB99"] = {n="Gefleckter Rotschenkel",f={'ND'}},
		["6E349"] = {n="Stachelkiebitz",f={'tW'}},
		["6E331"] = {n="Stachel-Wiesenpieper",f={'Ef'}},
		["6FFF8"] = {n="Gefleckter Kampfläufer",f={'Ag'}},
		["6BBB1"] = {n="Starkmoor-Eule",f={'Du'}},
		["6BC0D"] = {n="Hohltaube",f={'ND'}},
		["6E315"] = {n="Steinpieper",f={'tW'}},
		["6BBD6"] = {n="Schwarzkehlchen",f={'Lo'}},
		["6E33F"] = {n="Felssenken-Birkenzeisig",f={'Wf'}},
		["6FFB9"] = {n="Steinkratzer",f={'TW'}},
		["6BC15"] = {n="Steintal-Habicht",f={'Du'}},
		["6BB9D"] = {n="Starrenhuhn",f={'Sw'}},
		["6FF9B"] = {n="Streifenschwalbe",f={'Lh','TW'}},
		["6BC7F"] = {n="Kampfläufer",f={'Br'}},
		["6FFEA"] = {n="Sonnenfink",f={'Ar'}},
		["6BC14"] = {n="Schwalbe",f={'Ca','Lo'}},
		["6FFA7"] = {n="Pfeifschwalbe",f={'Bf'}},
		["6BC77"] = {n="Schwarzhuhn",f={'Du'}},
		["6E36B"] = {n="Holder Barde",f={'Ll'}},
        	["70007"] = {n="Süßlerche",f={'Ar'}},
		["6FFAD"] = {n="Schwallerpel",f={'Bf','Ld'}},
		["6B444"] = {n="Mauersegler",f={'Br','Lo'}},
		["6FFDA"] = {n="Tarlangs Specht",f={'Ld'}},
		["6BBB0"] = {n="Waldkauz",f={'EL'}},
		["6B443"] = {n="Krickente",f={'EL','Sh'}},
		["6BC05"] = {n="Triel",f={'Lo'}},
		["6FFFE"] = {n="Distling",f={'It','La'}},
		["6E33E"] = {n="Thrihyrne-Geier",f={'Wf'}},
		["6E30E"] = {n="Tinuviels Nachtigall",f={'Ll'}},
		["6FFC1"] = {n="Schopferpel",f={'Ar','It'}},
		["6FFB0"] = {n="Tumladen-Häher",f={'La'}},
		["6BBF6"] = {n="Turteltaube",f={'Ca'}},
		["6BBCA"] = {n="Hänfling",f={'En','Er'}},
		["6E382"] = {n="Untiefen-Strandläufer",f={'tW'}},
		["6BB89"] = {n="Valardis' Schwan",f={'Ev'}},
		["6FFBF"] = {n="Schleiernachtigall",f={'Lh'}},
		["6BC70"] = {n="Watwasserreiher",f={'Sw'}},
		["6FFB6"] = {n="Klagender Sänger",f={'Lh'}},
		["6E324"] = {n="Striemenmückenfänger",f={'Cl'}},
		["6FFD9"] = {n="Sumpfsänger",f={'Ag'}},
		["6FFA6"] = {n="Blassflitzer",f={'Ar'}},
		["6FFFA"] = {n="Wächter-Eule",f={'It'}},
		["6BBC5"] = {n="Wasserpieper",f={'Ca','Sw'}},
		["6BBD2"] = {n="Wasserralle",f={'Ev'}},
		["6BB8F"] = {n="Wettererpel",f={'Lo'}},
		["6FFF0"] = {n="Klagender Kranich",f={'TW'}},
		["6BC7B"] = {n="Trauertaucher",f={'An'}},
		["6BC20"] = {n="Klagefink",f={'An'}},
		["6E31B"] = {n="Trauereule",f={'Ll'}},
		["6E31E"] = {n="Westfold-Zweitmahdhuhn",f={'Wf'}},
		["6BBEE"] = {n="Steinschmätzer",f={'EL'}},
		["6FFC8"] = {n="Klagender Brachvogel",f={'Le'}},
		["6BBE7"] = {n="Braunkehlchen",f={'MM'}},
		["6BBB8"] = {n="Weißpieper",f={'Ev'}},
		["6BB7A"] = {n="Moorente",f={'En','Er'}},
		["6FF9F"] = {n="Weißschwanzkehlchen",f={'Le'}},
		["6BC17"] = {n="Seeadler",f={'EL'}},
		["6BBE6"] = {n="Wasseramsel",f={'Ev'}},
		["6E31D"] = {n="Weißflügel-Seeschwalbe",f={'Ew'}},
		["6BB8D"] = {n="Grasmücke",f={'ND'}},
		["6E383"] = {n="Wohin-Sänger",f={'Wf'}},
		["6E31C"] = {n="Wildnishammer",f={'tW'}},
		["6E387"] = {n="Fitis",f={'Ew'}},
		["6BC76"] = {n="Weidenhuhn",f={'Fo'}},
		["6FFCB"] = {n="Windschläger",f={'Le'}},
		["6BBD5"] = {n="Windfelseneule",f={'En'}},
		["6E380"] = {n="Weidenmaus",f={'Ew','Wf'}},
		["6E36E"] = {n="Waldpieper",f={'Ew'}},
		["6B44C"] = {n="Ringeltaube",f={'Br','Sh'}},
		["6BB64"] = {n="Heidelerche",f={'Tr'}},
		["6BBDC"] = {n="Bekassine",f={'Ca'}},
		["6E325"] = {n="Geistereule",f={'Mw'}},
		["6BC21"] = {n="Zaunkönig",f={'MM'}},
		["6FFC5"] = {n="Windekönig",f={'Lh'}},
		["6BC23"] = {n="Wendehals",f={'En'}},
		["6BC81"] = {n="Luch-Spatz",f={'Sh'}},
		["6BC24"] = {n="Schafstelze",f={'En','Du'}},
		["6E37C"] = {n="Gelbschnabeltaucher",f={'GR'}},
		["6B440"] = {n="Goldammer",f={'Tr','Er'}},
	}
BL_Bname = {}
for z,t in pairs(BL_Zone) do t.id = {} end
for id,t in pairs(BL_ID) do
	BL_Bname[t.n] = id
	for i,z in pairs(t.f) do
		local zt = BL_Zone[z]
		if not zt then Turbine.Shell.WriteLine("Bad zone code: "..z)
		else zt.id[id] = true end
	end
end